### ISSUE TITLE
glif file names

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#11]
In Glyphs I use the [glif name scheme from the ufo3 spec](http://unifiedfontobject.org/versions/ufo3/conventions.html#usernametofilename) as it makes much more sense.

**Comment by jamesgk** [comment]
Yea, for glyphs2ufo we're tied to whatever UFO library we use; I don't think robofab allows for this.

**Comment by moyogo** [comment]
RFont can have `lib["org.robofab.glyphNameToFileNameFuncName"]`.

**Comment by jamesgk** [comment]
glyphsLib has been using ufo3 naming ever since moving from Robofab to Defcon.
