### ISSUE TITLE
differences in default glyph order between CFF and TTF

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#111]
I noticed a difference in the glyph order generated by Glyphs.app depending on whether the exported font is CFF-OTF or TTF.

When an explicit "glyphOrder" custom parameter is defined, there is of course no difference, and glyphsLib also applies this (see https://github.com/googlei18n/glyphsLib/pull/108).

However, if I create an empty new font without a `glyphOrder` custom parameter, and then click Export, i see that the position of the "space" glyph changes depending on the output format.

If the font is exported as TTF, then the "space" glyph is placed in second position immediately after ".notdef", at index 1.

Whereas, if the output is a CFF-OTF, then "space" is not treated specially from the other glyphs, and is exported in whatever position it appears in the .glyphs source file (in the "Separator" section, which comes after "Letter, Latin").

@schriftgestalt, can you please confirm this is the case?
Is this done in order to comply with that old "First four glyphs" recommendation in the opentype specification? (Btw, that recommendation is no longer there in v1.8).

If this is the case, then we should update glyphsLib to match whatever Glyphs.app does.

You can see the difference in the ttx diff output:

```diff
--- /dev/fd/63	2017-02-08 12:18:54.000000000 +0000
+++ /dev/fd/62	2017-02-08 12:18:54.000000000 +0000
@@ -1,62 +1,62 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<ttFont sfntVersion="OTTO" ttLibVersion="3.6">
+<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.6">
 
   <GlyphOrder>
     <!-- The 'id' attribute is only for humans; it is ignored when parsed. -->
     <GlyphID id="0" name=".notdef"/>
-    <GlyphID id="1" name="A"/>
-    <GlyphID id="2" name="B"/>
-    <GlyphID id="3" name="C"/>
-    <GlyphID id="4" name="D"/>
-    <GlyphID id="5" name="E"/>
-    <GlyphID id="6" name="F"/>
-    <GlyphID id="7" name="G"/>
-    <GlyphID id="8" name="H"/>
-    <GlyphID id="9" name="I"/>
-    <GlyphID id="10" name="J"/>
-    <GlyphID id="11" name="K"/>
-    <GlyphID id="12" name="L"/>
-    <GlyphID id="13" name="M"/>
-    <GlyphID id="14" name="N"/>
-    <GlyphID id="15" name="O"/>
-    <GlyphID id="16" name="P"/>
-    <GlyphID id="17" name="Q"/>
-    <GlyphID id="18" name="R"/>
-    <GlyphID id="19" name="S"/>
-    <GlyphID id="20" name="T"/>
-    <GlyphID id="21" name="U"/>
-    <GlyphID id="22" name="V"/>
-    <GlyphID id="23" name="W"/>
-    <GlyphID id="24" name="X"/>
-    <GlyphID id="25" name="Y"/>
-    <GlyphID id="26" name="Z"/>
-    <GlyphID id="27" name="a"/>
-    <GlyphID id="28" name="b"/>
-    <GlyphID id="29" name="c"/>
-    <GlyphID id="30" name="d"/>
-    <GlyphID id="31" name="e"/>
-    <GlyphID id="32" name="f"/>
-    <GlyphID id="33" name="g"/>
-    <GlyphID id="34" name="h"/>
-    <GlyphID id="35" name="i"/>
-    <GlyphID id="36" name="j"/>
-    <GlyphID id="37" name="k"/>
-    <GlyphID id="38" name="l"/>
-    <GlyphID id="39" name="m"/>
-    <GlyphID id="40" name="n"/>
-    <GlyphID id="41" name="o"/>
-    <GlyphID id="42" name="p"/>
-    <GlyphID id="43" name="q"/>
-    <GlyphID id="44" name="r"/>
-    <GlyphID id="45" name="s"/>
-    <GlyphID id="46" name="t"/>
-    <GlyphID id="47" name="u"/>
-    <GlyphID id="48" name="v"/>
-    <GlyphID id="49" name="w"/>
-    <GlyphID id="50" name="x"/>
-    <GlyphID id="51" name="y"/>
-    <GlyphID id="52" name="z"/>
-    <GlyphID id="53" name="space"/>
+    <GlyphID id="1" name="space"/>
+    <GlyphID id="2" name="A"/>
+    <GlyphID id="3" name="B"/>
+    <GlyphID id="4" name="C"/>
+    <GlyphID id="5" name="D"/>
+    <GlyphID id="6" name="E"/>
+    <GlyphID id="7" name="F"/>
+    <GlyphID id="8" name="G"/>
+    <GlyphID id="9" name="H"/>
+    <GlyphID id="10" name="I"/>
+    <GlyphID id="11" name="J"/>
+    <GlyphID id="12" name="K"/>
+    <GlyphID id="13" name="L"/>
+    <GlyphID id="14" name="M"/>
+    <GlyphID id="15" name="N"/>
+    <GlyphID id="16" name="O"/>
+    <GlyphID id="17" name="P"/>
+    <GlyphID id="18" name="Q"/>
+    <GlyphID id="19" name="R"/>
+    <GlyphID id="20" name="S"/>
+    <GlyphID id="21" name="T"/>
+    <GlyphID id="22" name="U"/>
+    <GlyphID id="23" name="V"/>
+    <GlyphID id="24" name="W"/>
+    <GlyphID id="25" name="X"/>
+    <GlyphID id="26" name="Y"/>
+    <GlyphID id="27" name="Z"/>
+    <GlyphID id="28" name="a"/>
+    <GlyphID id="29" name="b"/>
+    <GlyphID id="30" name="c"/>
+    <GlyphID id="31" name="d"/>
+    <GlyphID id="32" name="e"/>
+    <GlyphID id="33" name="f"/>
+    <GlyphID id="34" name="g"/>
+    <GlyphID id="35" name="h"/>
+    <GlyphID id="36" name="i"/>
+    <GlyphID id="37" name="j"/>
+    <GlyphID id="38" name="k"/>
+    <GlyphID id="39" name="l"/>
+    <GlyphID id="40" name="m"/>
+    <GlyphID id="41" name="n"/>
+    <GlyphID id="42" name="o"/>
+    <GlyphID id="43" name="p"/>
+    <GlyphID id="44" name="q"/>
+    <GlyphID id="45" name="r"/>
+    <GlyphID id="46" name="s"/>
+    <GlyphID id="47" name="t"/>
+    <GlyphID id="48" name="u"/>
+    <GlyphID id="49" name="v"/>
+    <GlyphID id="50" name="w"/>
+    <GlyphID id="51" name="x"/>
+    <GlyphID id="52" name="y"/>
+    <GlyphID id="53" name="z"/>
   </GlyphOrder>
 
 </ttFont>
```

**Comment by schriftgestalt** [comment]
I can confirm this. There is a (outdated) recommendation somewhere that stated that the first four glyphs should be .notdef, null, CR and space in TrueType fonts. A lot people think that is a requirement and ask for it. There was even a bug in Pages that would place GID 1 next to page numbers with CFF fonts as they expected it to be nonprinting. 

If you have null (or NULL or .null) and CR, those will be reordered, too when exported as TTF.

**Comment by anthrotype** [comment]
Thanks for the confirmation.

I'm not sure what the right thing to do for glyphsLib is, since the output here is a UFO, not (yet) a TTF or a CFF.

If we reorder the four glyphs in the UFO but then produce a CFF from it, the default order won't match Glyphs.app (which doesn't reorder when the output is CFF). If we don't reorder the glyphs in the UFO and generate a TTF, it will have a different order from the one generated by Glyphs.app.

We could have ufo2ft always do such reordering but only when compiling TTFs, and whether or not the source UFO has a public.glyphOrder (or was produced by glyphsLib or not).

I mean, if one does have all the four (or some) recommended glyphs, one would want them to be placed as the first four, if anything.

**Comment by schriftgestalt** [comment]
The 'space/null/CR' are also reordered when you have a `glyphOrder`, unless you have a custom parameter that explicitly prohibits it. There are two options: `TrueType Keep GlyphOrder` and `DisableAllAutomaticBehaviour`. Both are not widely publicised, yet.

**Comment by anthrotype** [comment]
See https://github.com/googlei18n/fontmake/issues/252
