### ISSUE TITLE
Set width of glyphs with GDEF class 3 (mark) to zero?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#115]
James opened a similar issue on ufo2ft repo:
https://github.com/googlei18n/ufo2ft/issues/55

> I noticed that in fonts output by Glyphs, any glyph with GDEF class 3 has a width of zero. Should ufo2ft do the same? If so, we have to go back and change widths the compiled OTF/TTFs after the GDEF table has been compiled by feaLib.

I think it should be the job of glyphsLib to set the width of such mark glyphs to zero when building the UFO.

**Comment by anthrotype** [comment]
on second thought... I we use glyphsLib to generate UFO source files and we wish to be able to recreate the original .glyphs source back from them, maybe this zeroing-out of mark glyph advance widths/heights should not happen in here. Those generated UFOs may be considered source files to be further edited in another font editor, rather than simply a temporary byproduct of fontmake for the sake of generating binary OTFs.

So maybe this should be done in ufo2ft, as originally suggested in https://github.com/googlei18n/ufo2ft/issues/55

We could check if a `tabke GDEF {...}` with class definition is present in the `features.fea` (glyphsLib generates one automatically when building the UFOs), and if a glyph is a mark enforce its advance in the `{h,v}mtx` to be 0?

/cc @brawer @behdad

**Comment by punchcutter** [comment]
Aha, I see your point about dealing with the zeroing in ufo2ft. Even then it's possible that we don't want to zero. We also need to make sure we check the Glyphs custom parameter DisableAllAutomaticBehaviour before we do it.

**Comment by anthrotype** [comment]
I wonder, is there a specific custom parameter to disable this behaviour (i.e. zeroing out the advances of combining mark glyphs) as opposed to the general `DisableAllAutomaticBehaviour` one?

/cc @schriftgestalt

**Comment by schriftgestalt** [comment]
There is no custom parameter. It sets all marks with `subCategory == "Nonspacing"` to zero. If you need a spacing mark that still attaches, the subCategory needs to be set to `Spacing Combining`.

**Comment by schriftgestalt** [comment]
About the zeroing: I suspect that most people dealing with .ufo would expect the width of nonspacing marks set to zero. Last time I checked, other tools could not to the zeroing on export automatically. So doing it in the glyphsLib would make it easier to export the files. I don't expect to many people use glyphsLib to write .ufos and then like them to import back to Glyphs. That could be done with the build in UFO support. But if you like to ensure round tripping, then we could agree on a lib key that stores the original width.

**Comment by anthrotype** [comment]
I like the idea of storing the original width in a private key inside the UFO glyph's `lib` for the sake of roundtripping.
What about `com.schriftgestaltung.originalWidth`?

**Comment by schriftgestalt** [comment]
Sounds good. One problem with this. What happens if the user changes the width in the UFO? Maybe only apply the value when the width is zero?

**Comment by khaledhosny** [comment]
I think may be we are overthinking it? Just zero the width and be done with it (for some OpenType implementations, e.g. MS’s and HarfBuzz it does not really matter most of time as any glyph with GDEF mark class will be zerod by the engine). If it is really necessary the reverse can be done in the future UFO to Glyphs converter as even regular UFO’s will benefit from such treatment.

**Comment by schriftgestalt** [comment]
I agree but and automatic expanding of metrics is a bit dangerous, too. It might shift the placement of some components.

**Comment by jenskutilek** [comment]
It seems the variants of nonspacing marks are not processed by this logic. E.g. dieresiscomb is renamed to uni0308 and its width is set to 0, but dieresiscomb.case keeps its name and width.

This will lead to an extra space after composed letters on macOS, cf. https://github.com/jenskutilek/FiraSystemFontReplacement/issues/49

**Comment by anthrotype** [comment]
@jenskutilek glyphsLib simply applies the rules from the GlyphsData.xml. If a glyph name is marked with category "Mark" and subCategory "Nonspacing", then it sets the width to 0.
The glyph "dieresiscomb" is in that list, whereas "dieresiscomb.case" is not.

Can you confirm, does Glyphs.app automatically set the width of dieresiscomb.case to 0?

You can also override/extend the definitions from the GlyphsData.xml for selected glyphs and store their category/subCategory directly inside the .glyphs file: see  https://github.com/googlei18n/glyphsLib/issues/190#issuecomment-304280521

**Comment by jenskutilek** [comment]
Yes, I can confirm, that Glyphs.app sets all `.case` glyphs related to the main combining diacritics to 0 advance width. E.g. `dieresiscomb.case`. But other related variants keep their widths, such as `dieresiscomb.sc`.

@schriftgestalt, maybe you can clarify?

In addition to setting the width to 0, the outlines are also moved to the left, so the former RSB is now negative. But I think it’s not necessary to replicate this:

![screen shot 2017-09-12 at 18 46 24](https://user-images.githubusercontent.com/3185950/30338107-c0e9c308-97ea-11e7-9bc5-edec550770cd.png)

**Comment by schriftgestalt** [comment]
That the .sc accents are not set to zero width is a mistake. The others are correct and are controlled by the subCategory="NonSpacing". (that is actually the problem with the .sc as it gets a subcategory of "Smallcap".

**Comment by anthrotype** [comment]
I don't understand.. I only see "dieresiscomb" in the GlyphData.xml. What's exactly the logic with `.<suffix>` glyph names? Do they all inherit the category/subCategory of their base glyph (i.e. without the suffix)?

**Comment by schriftgestalt** [comment]
There is an algorithm that tries to get glyphData for Glyphs with suffixes and ligatures.
