### ISSUE TITLE
[parser] add support for binary data values

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#119]
The glyphsLib parser should support binary data values as defined in the ASCII property list specification:

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/PropertyLists/OldStylePlists/OldStylePLists.html

> NSData
> Binary data is enclosed in angle brackets and encoded in hexadecimal ASCII. Spaces are ignored.
> For example:
```
<0fbd777 1c2735ae>
```

see https://github.com/googlei18n/fontmake/issues/247#issuecomment-279165940

**Comment by anthrotype** [comment]
According to the above mentioned "OldStylePList" specification, the NSData enclosed in angle brackets should be encoded as "hexadecimal ASCII", however when I set some `userData` from within Glyphs.app and save the .glyphs file, I don't get hexadecimal ASCII, but a *base64-encoded* string:

```python
from Foundation import *
import base64

font = Glyphs.font

glyph = font.glyphs['a']

data = NSData.alloc().initWithBytes_length_('the bytes', 9)

glyph.userData["customUserData"] = data

# font.save()
#
# the following data is written:
#
#   customUserData = <dGhlIGJ5dGVz>;

print(base64.b64decode('dGhlIGJ5dGVz'))

# this will print:
#   the bytes
```

**Comment by anthrotype** [comment]
I suppose that the .glyphs format can no longer be considered equivalent to NeXTSTEP ascii plist.
So the glyphsLib parser should follow whatever Glyphs.app does; in this case, encode/decode strings enclosed in angle brackets as base64 rather than hexadecimal.

**Comment by anthrotype** [comment]
Oh jeez... :man_facepalming: 

It turns out that a `userData` attribute (a dict with arbitrary used defined content) can be contained, not just in a font, font master, glyph and layer (where it is encoded as Base64), but also inside a node. However, *in this case only* an NSData value will be encoded as *hexadecimal* string instead of Base64.

```python
from Foundation import *
import base64

font = Glyphs.font
glyph = font.glyphs['a']
data = NSData.alloc().initWithBytes_length_('the bytes', 9)
glyph.layers[0].paths[0].nodes[0].userData['customNodeUserData'] = data
font.save()
```

This is what you get in the .glyphs source: 
```
"328 -3 CURVE SMOOTH {\ncustomNodeUserData = <74686520 62797465 73>;\n}",
```

As you can see, it's an hex string:
```python
>>> from binascii import unhexlify
>>> unhexlify('74686520 62797465 73'.replace(' ', ''))
b'the bytes'
```

Also, why are the newlines escaped like this `\n` instead of using the octal notation used elsewhere `\012`?

I am about to give up.

**Comment by schriftgestalt** [comment]
Sorry for the mess. I’m cleaning it up right now and make it stick to the spec. That means at some point it will stick write correct plist. Do you have files that actually have <data> in the userData?

**Comment by anthrotype** [comment]
Thank you Georg!

I'm not sure about Noto fonts, but at least at DaMa we haven't used `userData` yet.
I was just trying to fix a related fontmake issue https://github.com/googlei18n/fontmake/issues/247 raised some weeks ago by Adam.

It's fine if old glyphs source files containing such incorrectly formatted userData can be fixed by re-saving them with newer Glyphs.app versions.

**Comment by anthrotype** [comment]
@schriftgestalt I'm still seeing the same issue with the latest Glyphs.app version 2.4.2 (1059).

`userData` is written as a base64 encoded string rather than as hexadecimal ASCII; except for the `customNodeUserData` inside a node's quoted string value, where hexadecimal notation is used.

Also, the newline is written as `\n` in the latter, whereas e.g. in the features code string it's written as octal escape `\012`.

If we want the glyphsLib parser/writer to support binary data, we need to know and handle these special cases.

**Comment by schriftgestalt** [comment]
I didn’t like to add that change in the 2.4 version. It will be in 2.5.

**Comment by anthrotype** [comment]
makes sense. Please let us know when you push that out, thanks

**Comment by belluzj** [comment]
Partial support is implemented in master (but maybe not the tricky bits like ignoring spaces and the different format inside node userData)

https://github.com/googlei18n/glyphsLib/blob/0a86327a93b3f324f200e35a23f639db4ae58280/tests/parser_test.py#L127-L131

**Comment by anthrotype** [comment]
what about the inconsistency between base64 and ascii hexadecimal in https://github.com/googlei18n/glyphsLib/issues/119#issuecomment-326930653

is that fixed now in latest Glyphs.app?

**Comment by schriftgestalt** [comment]
It writes userData as hexadecimal ASCII now.

**Comment by anthrotype** [comment]
If that’s the case, then we should do the same here. Does current Glyphs app still support files that instead have userData encoded as base64? Does it use some heuristic to distinguish it from hexadecimal ascii? Or checks the version number of the source file?

**Comment by schriftgestalt** [comment]
Glyphs tries to guess if it is base64 or hex data.

**Comment by anthrotype** [comment]
hm. but then it's ambigupus, as there could be strings that could be interpreted as either one of the two...

```python
>>> from base64 import b64decode
>>> from binascii import unhexlify
>>> s = "ABCDEF01"
>>> b64decode(s)
b'\x00\x10\x83\x10]5'
>>> unhexlify(s)
b'\xab\xcd\xef\x01'
```

**Comment by schriftgestalt** [comment]
There could be. Yes. But that is very unlikely with real world data, isn't it?

**Comment by anthrotype** [comment]
why is it unlikely? Say I want to store some arbitrary binary data in my userData. How can I make sure that it will be decoded in with the right codec?
You must know at which specific appVersion you did the change in the semantics of userData. We could use that to decided whether to unhexlify or b64decode

**Comment by schriftgestalt** [comment]
I’m 99% certain that there are no glyphs files that have data in the userdata that is ambiguous. But it is a good idea to check the version number.

**Comment by anthrotype** [comment]
ok, so from which version then?

**Comment by anthrotype** [comment]
I think #354 fixed this
