### ISSUE TITLE
production names

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#12]
Glyphs can store production names in the .glyphs file now. This is mainly useful i you need to work with different clients and different name requirements.

This should be supported by glyphs2ufo. The biggest problem its that the feature code needs to be converted. I have some code in Glyphs that I could port over to python but maybe there is something already there.

**Comment by twardoch** [comment]
@schriftgestalt has just published a subset of GlyphData.xml (just the basic stuff i.e. Unicode-to-Glyphs-glyphname mapping and some categorization, without the additional metadata) under the MIT license: 
https://github.com/schriftgestalt/GlyphsInfo

This can be used as an auxiliary source for converting the internal Glyphs glyphnames into production glyphnames.

**Comment by jamesgk** [comment]
> The biggest problem its that the feature code needs to be converted. I have some code in Glyphs that I could port over to python but maybe there is something already there.

All the feature code in a UFO is stored in a single plaintext file, so maybe just some simple find+replace operations would be sufficient? Another concern is that components are referenced by glyph name. Not sure if there's anything else.

**Comment by behdad** [comment]
Renaming at the end sounds more robust to me.  find+replace sounds scary.

**Comment by jamesgk** [comment]
Is there an easy way to do renaming with fontTools?

**Comment by twardoch** [comment]
The basic principle is: UFO uses glyph names which are not necessarily PostScript glyph names at all. The FEA code “sort of” uses PostScript glyph names, but the assumption is that they’re not necessarily that (especially since AFDKO now accepts characters in glyph names used within FEA which are not valid characters within PostScript glyph names). 

There is currently no way to store PostScript glyph names in UFO. I opened a discussion 19 months ago: 
* https://groups.google.com/forum/#!topic/ufo-spec/pJnk5x1_6pE
* https://github.com/unified-font-object/ufo-spec/issues/9
but it hasn’t gone very far. 

AFDKO uses its own GOADB file which allows glyph renaming **after** the GSUB/GPOS tables have been compiled.

**Comment by behdad** [comment]
> Is there an easy way to do renaming with fontTools?

It's not complete, but can be done.  See https://github.com/behdad/fonttools/issues/149

**Comment by khaledhosny** [comment]
I recently needed a way to set production names in UFO files as well, may be we can agree on something in the glif lib and then ufo2ft and other tools would use it?

**Comment by schriftgestalt** [comment]
Maybe glif > lib > public.productionname?

**Comment by khaledhosny** [comment]
Or maybe postscriptName instead of productionname similar to the suggestion in https://groups.google.com/forum/#!topic/ufo-spec/pJnk5x1_6pE and to be an indicator that it needs to be a valid PostScript name?

**Comment by twardoch** [comment]
I did like `public.postscriptName` suggested by @typesupply — it fits with other `postscript*` entries in [fontinfo](http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/) and makes it obvious what its purpose is.

**Comment by schriftgestalt** [comment]
Would you call the names in a TrueType file postscript, too? And postscriptsname sounds like one of the entries in the name table. And it is even longer.

**Comment by twardoch** [comment]
...purpose but also heritage and set of restrictions etc. And after all in OT fonts, this name lives in the “[the PostScript table](https://www.microsoft.com/typography/otspec/post.htm)” (`post`) or in the `CFF ` table which in its spec makes heavy references to PostScript.

**Comment by twardoch** [comment]
@schriftgestalt Of course I would. They are only needed for PostScript and PDF anyway, and are optional in TrueType-flavored fonts. And they live in the “PostScript table” (official spec name)

**Comment by schriftgestalt** [comment]
I'm fine with both.

**Comment by jamesgk** [comment]
So I think we want to populate `public.postscriptName` using  1) the "production" field if present in the .glyphs data, or else 2) the production name in [GlyphData.xml](https://raw.githubusercontent.com/schriftgestalt/GlyphsInfo/master/GlyphData.xml) for this glyph.

I wonder how best to use info from GlyphData.xml? Should the file just be copied to glyphsLib?

**Comment by anthrotype** [comment]
I suggest we add the @schriftgestalt GlyphsInfo repository as a submodule for glyphsLib, and install the GlyphData.xml file though setuptools' "package_data".

**Comment by anthrotype** [comment]
And then we could use pkg_resourced.resource_filename() to retrieve the path to the packaged GlyphData.xml.

**Comment by jamesgk** [comment]
Hmm. I wonder how valuable the data in GlyphData.xml really is, and whether that's worth doing. As far as I can tell it only specifies production names for glyphs with unicode values, using a "uniXXXX" pattern that's easy enough to do manually. Though, it also only specifies production names past uni0180 (with some seemingly arbitrary exceptions?)

**Comment by schriftgestalt** [comment]
Entries in the GlyphData without a production name are most likely in AGLFN. The glyph list is helpful to map names to unicodes, e.g. If you need to find the Unicode of the base name for glyphs with suffixes.

**Comment by jamesgk** [comment]
> The glyph list is helpful to map names to unicodes, e.g. If you need to find the Unicode of the base name for glyphs with suffixes.

That's a good point. Though, this is possible with loaded UFOs too. Something like

```python
basename, suffix = name.split('.')
prodname = glyphData[basename]['production'] + '.' + suffix
# could be swapped out with
prodname = 'uni' + hex(ufo[basename].unicode) + '.' + suffix
# or even
prodname = ufo[basename].lib['public.postscriptName'] + '.' + suffix
```

Anyways, it's obvious we should at least use production names as they appear in Glyphs sources, so I'll open a PR with that for now.

**Comment by anthrotype** [comment]
Thanks Sascha!
So I guess the next steps will be tagging a v1.3.0 release for glyphsLib, bumping the minimum `install_requires`  of fontmake to `"glyphsLib>=1.3"`, and finally release a new fontmake v1.2.0.
I can do that, unless you have other stuff to push to glyhpsLib.
