### ISSUE TITLE
do not generate inactive instances

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#129]
When an instance has the `is active` checkbox switched off in the font info, then Glyphs.app does not generate the instance.

In the glyphs source this corresponds to a `exports = 0` attribute in that instance's data.

glyphsLib should check and do the same, i.e. not generate instances that are flagged as inactive.

**Comment by brawer** [comment]
The current code looks for an instance attribute called `active`. But at least with Glyphs 2.4, the attribute is indeed named `exports`. Fix coming.
