### ISSUE TITLE
Use same defaults as Glyphs for underlineThickness and underlinePosition

### ISSUE THREAD

**Issue by brawer** [googlei18n/glyphsLib#131]
According to page 200 of the [Glyphs documentation](https://glyphsapp.com/content/1-get-started/2-manuals/1-handbook-glyphs-2-0/Glyphs-Handbook-2.3.pdf#page=200), Glyphs assumes specific defaults for `underlineThickness` and `underlinePosition` when these attributes are not present in the source:

> **underlinePosition** _integer_ The suggested distance from the baseline to the top of the underline. Negative values indicate a position below the baseline. Corresponds to the CFF table entry UnderlinePosition. Default is –100.

> **underlineThickness** _non-negative integer_ Underline thickness value. Corresponds to the CFF table entry UnderlineThickness. Default is 50.

The current glyphsLib code does not supply these defaults. Also, there’s currently no unit tests for the conversion of these parameters.

**Comment by anthrotype** [comment]
There's a set_default_params function in the builder module now which can be used for this sort of things.

**Comment by zjusbo** [comment]
Resolved.
