### ISSUE TITLE
not using weightClass custom parameter when setting the generated ufo.info.openTypeOS2WeightClass

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/glyphsLib#135]
this is a glyphsLib version of https://github.com/googlei18n/fontmake/issues/224

which had the following comment:
"as @moyogo explained in https://github.com/googlei18n/fontmake/issues/224#issuecomment-269011274 , it looks like this is glyphsLib issue (not using weightClass custom parameter when setting the generated ufo.info.openTypeOS2WeightClass), so it should be re-opened under https://github.com/googlei18n/glyphsLib/issues/new"

**Comment by anthrotype** [comment]
Sascha fixed it with https://github.com/googlei18n/glyphsLib/commit/66f9885fe56a2e4f739157a8615374c006728553

**Comment by anthrotype** [comment]
The patch is still only in glyphsLib master and not yet released.
Let's keep this issue open until we have tagged a new glyphsLib release and bumped fontmake's requirements.
