### ISSUE TITLE
.fea syntax now allows dashes in glyph names

### ISSUE THREAD

**Issue by behdad** [googlei18n/glyphsLib#148]
@brawer is this implemented in feaLib already?

We should confirm that, then remove the "Illegal glyph name..." warning from glyphsLib, and remove the code that changes them to underscore.

**Comment by behdad** [comment]
Actually, maybe this is fixed already?

**Comment by brawer** [comment]
Yes, this was removed from glyphsLib in https://github.com/googlei18n/glyphsLib/commit/c283d6ec4d7d9898489915d325e2925b8a33b542. See https://github.com/googlei18n/fontmake/issues/249 for background.

**Comment by anthrotype** [comment]
> is this implemented in feaLib already?

yes, feaLib supports hyphens in glyph names since fonttools>=3.7.0
