### ISSUE TITLE
parse into object tree instead of dict

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#15]
What if we could pares into an object tree instead of a dict. That would allow easier modification of the data, to be able to use it like roboFab but with native Glyphs objects. With full access to instance and all layers. 

I’m not so familiar with best practices in Python so I could use a hint on how to implement it. How to tell the parser what class it should use for what piece of the file?

**Comment by jamesgk** [comment]
I'm not sure if this can be done as simply as the parsing code we have now. Though maybe someone else would have some ideas. Defining and building native Glyphs objects seems like a big task to me, which is why I've been fine with using native python types.

**Comment by behdad** [comment]
It wouldn't bee too hard to add this to casting.py.  We'd just need to instantiate the class then set `__dict__` on the object instance directly.  I'm not sure what we gain from this though.  Perhaps we can implement this when we support writing to Glyphs file.

**Comment by schriftgestalt** [comment]
It wouldn't be useful for the current use case but will expand it quite a bit. 

I'll have a look at the casting.py.

**Comment by schriftgestalt** [comment]
I’m just playing around with the code. Shouldn’t the module called `glyphslib` with a submodule `glyphs2ufo`?

**Comment by schriftgestalt** [comment]
Is there a clear policy to use tabs or spaces for indentation? The files use both, I prefer tabs.

**Comment by schriftgestalt** [comment]
I have put something together in the `ClassTree` branch. It uses the parser but user the proper classes instead of a dict. This is done by storing the class in `self.dict_type`. Each class has a key2class dict that is used to update the dict type. This should make the extra `cast_data()` unnecessary. All special cases can be dealt with in the setter of the containing classes.

**Comment by davelab6** [comment]
On 23 February 2016 at 08:48, Georg <notifications@github.com> wrote:

> Is there a clear policy to use tabs or spaces for indentation? The files
> use both, I prefer tabs.
>

https://google.github.io/styleguide/pyguide.html ?

**Comment by behdad** [comment]
> https://google.github.io/styleguide/pyguide.html ?

We don't have to follow this.

I personally prefer tabs, but looks like some people have gravitated towards spaces.

**Comment by behdad** [comment]
> I have put something together in the ClassTree branch. It uses the parser but user the proper classes instead of a dict. This is done by storing the class in self.dict_type. Each class has a key2class dict that is used to update the dict type. This should make the extra cast_data() unnecessary. All special cases can be dealt with in the setter of the containing classes.

Well, you essentially reimplemented the casting.  The nice thing about casting.py was that it was coming straight from your documentation: https://github.com/schriftgestalt/GlyphsSDK/blob/master/GlyphsFileFormat.md

so if you like to change that to refer to classes, we can switch to that.

Also, does this make glyphs2ufo API close to what your internal Python API is?  Should we aim for that?

**Comment by schriftgestalt** [comment]
> Well, you essentially reimplemented the casting.

The current implementation first converts everything into dicts to convert it again into something else. IMHO this is waist of performance/memory. If we one tries to open a MM CJK font with several masters you should see a difference. 

Short term the difference is that my approach has the advantages/disadvantages of object oriented programming.

> Also, does this make glyphs2ufo API close to what your internal Python API is? Should we aim for that?

The .glyphs files follow the internal objectiveC APIs. The python APIs differ a bit but we should be able to wrap that.

**Comment by twardoch** [comment]
It would of course be wonderful if the glyphsLib object-oriented API was at least largely similar to https://docu.glyphsapp.com/ even if it only implemented a subset of the functionality of the full Glyphs API. Kind of like the difference between the  "FontLab" and "NoneLab" worlds in RoboFab where the latter only implemented a subset of the functionality.

**Comment by schriftgestalt** [comment]
This is the plan ;)

**Comment by m4rc1e** [comment]
I've started modifying some of my glyphsapp scripts to work with both glyphsLib and Glyphsapp. I need this functionality because I'd like to batch run my qa tools on a collection of .glyphs files, from the cmdline. I echo twardoch's sentiments. Having the same attributes as the Glyphsapp python api is a winner.

@schriftgestalt how are you progressing with this?
I've written a very rudimentary wrapper myself.

**Comment by schriftgestalt** [comment]
I  pythons skills and my time are not

**Comment by jamesgk** [comment]
I think we should keep this open, though neither Georg or I seem to have time to work on it in the foreseeable future. We at least agree that it would be nice to have.

**Comment by m4rc1e** [comment]
I'll send a pr in a week or so.

**Comment by schriftgestalt** [comment]
I didn't mean to close it. Was trying to answer in the train. 

I don't have enough python skills and time to properly set this up. But am willing to help out as much as I can.
