### ISSUE TITLE
Instance locations are written in non-deterministic order

### ISSUE THREAD

**Issue by brawer** [googlei18n/glyphsLib#165]
Sometimes, tests are broken because instance locations seem to be written in non-deterministic order. See https://travis-ci.org/googlei18n/glyphsLib/jobs/221004107 for an example. I’m working on a fix.

**Comment by brawer** [comment]
We didn’t notice before because until today, all unit tests were using single-axis fonts.

**Comment by anthrotype** [comment]
good catch
