### ISSUE TITLE
hardcoded axes default locations with no "base" master break varLib

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#170]
See https://github.com/googlei18n/glyphsLib/pull/161#discussion_r111366461

we should get that value from somewhere else, possibly another custom parameter.

/cc @schriftgestalt

**Comment by schriftgestalt** [comment]
I’m plaining to add a custom parameter to give more control over the axes...

**Comment by behdad** [comment]
The default should come from whatever master gets its info attribute set to True. @brawer can you do that?

When Georg adds the custom parameter, we can use that.

**Comment by brawer** [comment]
Well, current Glyphs doesn’t store axis values (in particular, the CSS weight class) on the masters; those can only be found on the instances. But I’ll see what I can do.

**Comment by schriftgestalt** [comment]
Do you have a suggestion for the custom parameter keys? There will be one in the font like: `OTVar axes` and one in each master `OTVar axis positions`. Does this sound right?

**Comment by schriftgestalt** [comment]
Or skip the `OTVar`. Just `Axes` and `Axis Positions`?

**Comment by moyogo** [comment]
`Axes` and `Axis Positions` sound good. `Axis Location` could work as well.

**Comment by anthrotype** [comment]
Maybe we should get such base master from the the new "Variation Font Origin" custom parameter? This

> allows defining the OTVar origin master. It takes the master name as value

https://glyphsapp.com/blog/glyphs-2-4-1-released

**Comment by behdad** [comment]
> Axes and Axis Positions sound good. Axis Location could work as well.

Location has become more widespread.

**Comment by behdad** [comment]
> Maybe we should get such base master from the new "Variation Font Origin" custom parameter? This
> 
>     allows defining the OTVar origin master. It takes the master name as value
> 
> https://glyphsapp.com/blog/glyphs-2-4-1-released

Yes, that's the one I was talking about that I remember Georg announced at his talk.

At any rate, if that's not available, we should get location for master that is getting `<info copy="1">` set.  I understand that masters don't have location; but we are already extracting the mapping, so that argument does not make sense to me.  It's just more work to find the right number, but certainly doable.

**Comment by brawer** [comment]
Sure, of course. I’m on vacation this week, but (as said before) I can look into this at some point.

**Comment by behdad** [comment]
Thanks. No rush.

**Comment by brawer** [comment]
Regarding the newly added glyphsLib parameter, let’s do that in a separate change; see https://github.com/googlei18n/glyphsLib/issues/176.

**Comment by schriftgestalt** [comment]
I just added the mentioned parameters. The structure is as follows:

in font.customParameters:
```
customParameters = (
	{
		name = Axes;
		value = (
			{
				Name = Weight;
			},
			{
				Name = Width;
			},
			{
				Name = Sonstwas;
			},
			{
				Name = "Optical size";
			}
		);
	}
);
```
And for each master:
```
customParameters = (
	{
		name = "Axis Location";
		value = (
			{
				Axis = Weight;
				Location = 400;
			},
			{
				Axis = Width;
				Location = 5;
			},
			{
				Axis = Sonstwas;
				Location = 123;
			},
			{
				Axis = "Optical size";
				Location = 3;
			}
		);
	}
);
```
Please comment if it doesn’t fit.

**Comment by brawer** [comment]
What about the axis tags for the `fvar` table? For standard registered axes like `Weight` or `Optical size`, a compiler could of course have a built-in mapping. But for custom axes like `Sonstwas`, the compiler will need a four-letter tag such as `SNSW`.

**Comment by schriftgestalt** [comment]
```
customParameters = (
	{
		name = Axes;
		value = (
			{
				Name = Weight;
				Tag = wght;
			},
			{
				Name = Width;
				Tag = wdth;
			},
			{
				Name = Sowas;
				Tag = SOWA;
			},
			{
				Name = "Optical size";
				Tag = opsz;
			}
		);
	}
);
```

**Comment by anthrotype** [comment]
Thanks Georg for the proposal.

So to recap and make sure I understood; the main reason we need these extra font-wide and master-specific custom parameters is to build the designspace `<axes>` element that will be consumed by varLib to generate the variable font's fvar, avar, etc., or by MutatorMath to interpolate the instance UFOs.

You suggested an `Axes` font custom parameter containing a list of dictionaries, each containing a `Name` and a `Tag` value. Then, for each master, an `Axis Location` custom parameter, containing list of dictionaries, each defining the user-space `Location` of that master along a given `Axis`.

I guess we should assume that if a master does not have an `Axis Location` custom parameter, then its user-space location is the same as its interpolation-space location? By interpolation-space location I mean the master's `weightValue`, `widthValue` and `customValue` attributes.

Where do we get the default, maximum and minimum locations along each axis? The default could be the location of the "Variation Font Origin" master. The minimum and maximum could be the minimum and maximum locations among all the masters, though one may wish to use different values (e.g. to extrapolate).

And what about the `labelname` which defines the user-facing, localised name for the axis? Is that what you mean by the `font.customParameters['Axes'][0]['Name']`? If so, where do we get the required `xml:lang` code?

It would be good if you could model your new custom parameters after the https://github.com/LettError/designSpaceDocument, so we could more easily translate between the two.

**Comment by schriftgestalt** [comment]
I was thinking about adding a third field to hold the 'Default' axis value (right now I pick the min value).
With the next version, for variable font export, I require an 'Axes' parameter and an 'Axis Location' in each master. But could also default to the interpolation space if a value is missing.

The minimum and maximum is derived from the masters. Would it make sense to have that differently.

What do you mean with `xml:lang` code? You mean for localized axis names? I didn’t though about this, yet.

**Comment by moyogo** [comment]
> axisNameID: The name ID for entries in the 'name' table that provide a display name for this axis.

Any name ID can be localized. Multiple name record can have the same nameID and have different language IDs.

**Comment by anthrotype** [comment]
let's continue tracking this on #280
