### ISSUE TITLE
Support "Reencode Glyphs" custom parameter

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#205]
From the Glyphs Handbook (p. 194):

**Reencode Glyphs** *list* Takes a comma-separated list of ‘glyphname=unicodevalue’ pairs, e.g., ‘smiley=E100, logo=E101’. The parameter assigns the Unicode value to the glyph with the speci ed name at export. Should the Unicode value in question already be assigned to another glyph, the Unicode value of that other glyph will be deleted, but all production names will remain intact. It will remove a glyph’s Unicode assignment if the Unicode value is left out, e.g., ‘f_f_i=, f_f_j=’ will strip f_f_i and f_f_j from their Unicode value.

**Comment by JelleBosmaMT** [comment]
The handbook is wrong, with regards to input in the UI. It is one entry per line. See https://forum.glyphsapp.com/t/re-encoding-with-custom-parameter/6023/7.

**Comment by punchcutter** [comment]
Sources that use Reencode Glyphs are 

Noto Sans Bengali UI
Noto Sans Devanagari UI
Noto Sans Kannada UI
Noto Sans Malayalam UI

The currently generated UI instances for these are all incorrect because Reencode Glyphs is not implemented.
