### ISSUE TITLE
also write PreFilter custom parameters to ufo lib

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#214]
same as `Filter`, but applied before decomposition of composite glyphs

related issues:
https://github.com/googlei18n/noto-source/issues/84
https://github.com/googlei18n/fontmake/issues/275
https://github.com/googlei18n/ufo2ft/issues/120

**Comment by anthrotype** [comment]
In ufo2ft, to distinguish between what Glyphs.app calls `PreFilter` and (post) `Filter`, I added a boolean element `pre` to the filter structure, `true` means is a `PreFilter` (ie. should by applied before decomposition of composite glyphs), `false` or missing, it's a regular `Filter` to be applied after composite glyph decomposition:

https://github.com/googlei18n/ufo2ft/blob/abcd854910351b5a490ea1ead2a3a3075c4b61f0/Lib/ufo2ft/filters/__init__.py#L47-L50

If that's ok with you, I'm going to add that to glyphsLib's `parse_glyphs_filter` function.

/cc @moyogo @belluzj

**Comment by belluzj** [comment]
OK, noted

**Comment by schriftgestalt** [comment]
> (ie. should by applied before decomposition of composite glyphs)

The pre filter is called before removing overlap, the normal filter after.

**Comment by anthrotype** [comment]
Wait... the Glyphs handbook describes "PreFilter" as "Same as Filter, but applied before _decomposition_", and also elsewhere "If you want to apply filters before decomposition, use these values with the PreFilter property".
At least I understand "decomposition" as decomposition of composite glyphs.

It's important that there is a way to apply a filter before the decomposition of composite glyphs (which in turn normally happens before remove overlap). E.g. a transformation that applies to all glyphs in the font: in CFF format, all the composites are decomposed anyway so there's no much difference if that transformation is applied as a Filter or PreFilter, but in TTF where there are components, if the Filter is applied to all glyphs in the font, including the composite glyphs, then these are transformed multiple times, both as such and because their base glyphs were transformed.

Whereas, if one applies a PreFilter (as I understood it, before decomposition) including only to the contour glyphs (i.e. those that don't contain any components, but may be used as components in other composite glyphs) before the decomposition of composite glyphs (which means all composites in CFF, or only mixed contour/component glyphs or transformed/overlapping components in TTF), then one can produce both CFF and TTF fonts from the same glyphs source file and filter specification.

See this issue https://github.com/googlei18n/noto-source/issues/84

**Comment by anthrotype** [comment]
and elsewhere in the handbook, it says "Filter" are triggered 

> after decomposition of compound glyphs

**Comment by schriftgestalt** [comment]
Then this need to be fixed.

**Comment by anthrotype** [comment]
Then please explain how this is supposed to work. I've been working with these assumption in mind for the past few weeks to add support for export-time custom filters in ufo2ft.

**Comment by schriftgestalt** [comment]
I hade another look at the code. The handbook is not wrong after all. But also not complete. `PreFilter` is applied before decomposition and remove overlap. Then follow the `Filter`.

**Comment by anthrotype** [comment]
Yes, exactly as I thought! Thanks for confirming that :)
