### ISSUE TITLE
Double unicodes

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#216]
One other change coming with 2.5 is the support for more then one unicode per glyph. It is stored in the file like this:
```
unicode = "005A,007A";
```
(I first tried to skip the quotes, too. But neither Apples code nor the glyphslib parser liked it ;)

Internally, this is handled by two properties. One called `unicode` and it returns the first unicode if any. Then there is a `unicodes` property as an NSOrderedSet.

I though about changing the key in the file to `unicodes` but that doesn’t make a lot of sense. 

One reason why I didn’t use a list (like `unicode = (005A, 007A);`, is at the double unicodes are now commonly used and having either the parenthesis in all cases or different cases (a string for single and a array for multi) would be more complicated.

**Comment by anthrotype** [comment]
I would argue that even for a single unicode value there should be quotes, in order to disambiguate the hexadecimal representation of unicode values from similar (unquoted) decimal numbers (e.g. `1234` can be interpreted both as an hexadecimal string and as a decimal number).
You said elsewhere that you use quotes to make clear that a string that's only composed of digits is actually a string and not a numeric value.

**Comment by brawer** [comment]
Just to clarify, is this new mechanism intended for glyphs that are shared by multiple codepoints, for example `unicode = "0071,0430"` for an `a` glyph that is identical for U+0061 and U+0430? Whereas this mechanism is explicitly not for glyphs that correspond to some _sequence_ of Unicode codepoints, such as a `c_t` ligature glyph for U+0064 followed by U+0074?

**Comment by anthrotype** [comment]
I believe it's the former, like in the UFO spec.

**Comment by schriftgestalt** [comment]
It is intended for double encoding one glyph, not for a sequence. 

> You said elsewhere that you use quotes to make clear that a string that's only composed of digits is actually a string and not a numeric value.
But I also said that the unicode property is an exception and doesn’t need quotes.

**Comment by anthrotype** [comment]
> But I also said that the unicode property is an exception and doesn’t need quotes.

yeah.. my point was just that exceptions like this only make life more complicated.

The old-style plist format already can't distinguish between strings, numbers or boolean types: e.g. `value = 1` could be equally parsed as any three of them (that is, without contextual knowledge of the type associated with a particular attribute).

Using a consistent quoting scheme would allow at least to distinguish between strings of digits and actual numeric values (as for `bool`, it is a kind of `int` in Python anyway).

I'm still wrapping my head around the proposed class structure and the way the parser and writer were changed to accommodate that. I'll try to articulate my thoughts more clearly once I get the chance.

**Comment by dougfelt** [comment]
Personally, I really don't see that it's necessary in the glyphs file to
represent in any way the type of the value.  The type is wholly determined
by the use Glyphs makes of it. The location and keyword are sufficient to
identify the type of the value.  All that's necessary in the Glyphs file is
that tokenization be unambiguous.

**Comment by schriftgestalt** [comment]
+1

There are some places where the preservation of type matters. That is mostly the userData and some of the customParameters.

**Comment by belluzj** [comment]
@anthrotype Should this be fixed for the new release?

**Comment by anthrotype** [comment]
I don't have any rush releasing 2.0, I first want to figure out #214.
So if @belluzj would like to work on this one, please do thanks!

**Comment by anthrotype** [comment]
@belluzj is this fixed in current master?

**Comment by moyogo** [comment]
@anthrotype yes, it is:
https://github.com/googlei18n/glyphsLib/blob/0a86327a93b3f324f200e35a23f639db4ae58280/Lib/glyphsLib/builder/glyph.py#L36
https://github.com/googlei18n/glyphsLib/blob/0a86327a93b3f324f200e35a23f639db4ae58280/Lib/glyphsLib/builder/glyph.py#L139-L140

**Comment by anthrotype** [comment]
thanks!

**Comment by belluzj** [comment]
It can even read the version without quotes like `unicode = 005A,007A;` because it turns out that Glyphs 2.4.4 writes it that way
