### ISSUE TITLE
kern vs dist does not match Glyphs output

### ISSUE THREAD

**Issue by punchcutter** [googlei18n/glyphsLib#223]
Kerning on most Indic scripts is put into the dist feature on export, but when exporting a UFO either from Glyphs directly or using glyphsLib all kerning is placed in the kerning.plist. When exporting OTF/TTF from Glyphs the kerning is split so that LGC kerning is put in the kern feature and Indic kerning is put in the dist feature. 

@schriftgestalt Is it all (only) Indic scripts that get dist? Any others? Should we apply the same logic here? How do you determine what gets dist and what gets kern? 

I don't think it's ideal to automatically put something in either kern or dist only based on script, but in this case I would like to see glyphsLib act like Glyphs and split kern and dist the same way so that we get the same result.

**Comment by punchcutter** [comment]
In Glyphs custom code (like contextual GPOS) for each instance can be added with the 'Replace Feature' custom parameter so first we need that to work in glyphsLib which is what this pull request does: https://github.com/googlei18n/glyphsLib/pull/222. 

When exporting from Glyphs with a 'Replace Feature' containing dist code (for Indic scripts) Glyphs adds two dist features, one from the kerning and one from the Replace Feature. What we really want is to make one dist with the "kerning" first and any custom code added next.

**Comment by anthrotype** [comment]
> How do you determine what gets dist and what gets kern?

I'd also like to know how this works.
Maybe the generation of such `dist` feature should be the job of ufo2ft, perhaps extending the current KernFeatureWriter (/cc moyogo).

**Comment by schriftgestalt** [comment]
I fixed the duplicate dist feature already. And added support for abvm and blwm.

**Comment by punchcutter** [comment]
I was also thinking maybe it should be handled elsewhere, but glyphsLib is what pulls the kern info from the source so it seems like it should be split into kern/dist there to match what Glyphs does. builder.py is also where the features.fea text is getting created so if we just split the features here then that would be simple.

**Comment by punchcutter** [comment]
Well, if the duplicate dist feature is fixed in Glyphs then that's another thing to check here. If we do split the kern/dist in glyphsLib AND there is a Replace Feature for dist then I think merging them here in builder makes sense.

**Comment by schriftgestalt** [comment]
All kerning between glyphs that belong to Indic scripts is put into dist. I’ll have a look at the code to give a more detailed description.

**Comment by punchcutter** [comment]
@schriftgestalt Yes, that's what I expected, but for unencoded glyphs or something with a name not in the GlyphData.xml what happens? I assume that doesn't get in dist if it can't be determined what script it belongs to. For that situation maybe the best thing to do is make sure the Glyphs file has the script set correctly for each glyph?

**Comment by schriftgestalt** [comment]
> but for unencoded glyphs or something with a name not in the GlyphData.xml what happens

I have a quite strong heuristic that can find for all glyphs of interest. Cutting of suffixes and separate ligatures...

About the `kern/dist` split. All pairs that contain an Indic glyph are put in `dist`.

**Comment by anthrotype** [comment]
since glyphsLib lacks such heuristic, for the time being @punchcutter could set the script manually for those unencoded glyphs using the Command+Alt+I panel.

**Comment by punchcutter** [comment]
@anthrotype How categories are set isn't the issue at all. This issue is all about the fact that Glyphs creates both a dist and a kern feature, but glyphsLib does not which means running Indic scripts through glyphsLib produces incorrect fonts. They only get kern which is bad. Simply put, we can't deliver some Noto files because this kern/dist creation is broken (i.e. not implemented at all) in glyphsLib.

**Comment by anthrotype** [comment]
Ok. We shall try to prioritize this then.

**Comment by anthrotype** [comment]
> added support for abvm and blwm

@schriftgestalt we will need to add support for that in our pipeline to match Glyphs.app output.
Would you like to share how Glyphs.app generates those?

**Comment by schriftgestalt** [comment]
The code to create mark and abvm/blwm is very similar. 
First split all glyphs by Indic script and all other. For the first group, put all anchors with a name in (‘top’, ‘topleft’, ‘topright’, ‘candra’, ‘bindu’, ‘candrabindu’) into abvm and all (‘bottom’, ‘nukta’, ‘bottomleft’, ‘bottomright’) in blwm. All others are checked if they are in the top or bottom part of he letter.

**Comment by anthrotype** [comment]
@schriftgestalt thanks for the info. Could also you give us the list of "Indic" scripts that Glyphs.app considers for inclusion in this dist/abvm/blwm auto-generated features?

**Comment by anthrotype** [comment]
The dist feature generation should be fixed by https://github.com/googlei18n/ufo2ft/pull/255
FYI i'm now working on the abvm/blwm features
