### ISSUE TITLE
Make anchor propagation optional

### ISSUE THREAD

**Issue by jvgaultney** [googlei18n/glyphsLib#234]
Currently to_ufos() assumes that anchors from parent glyphs' components should be copied to the parent using propagate_font_anchors(). However useful that may be, it's not always desired. In fact, it introduces problems when you've intentionally removed certain anchors in composite glyphs. Inappropriate anchors get added, and there's no way to turn it off.

Please add an argument to to_ufos() that turns propagation off. Then that argument would need to be added to load_to_ufos(), build_masters(), and build_instances().

**Comment by anthrotype** [comment]
I agree, we should make this optional as it may not be desirable in some workflows.

**Comment by jvgaultney** [comment]
Would a pull request from me for that additional option be welcomed?

**Comment by anthrotype** [comment]
it certainly will!

**Comment by anthrotype** [comment]
Fixed #237
