### ISSUE TITLE
com.schriftgestaltung.useNiceNames should be boolean

### ISSUE THREAD

**Issue by DavidRaymond** [googlei18n/glyphsLib#247]
com.schriftgestaltung.useNiceNames should be a boolean value in the UFO rather than integer.

So, in ufo.py, this section needs updating:

```
        # deal with any Glyphs naming quirks here
        if name == 'disablesNiceNames':
            name = 'useNiceNames'
            value = int(not value)
```
Also, for that section, Glyphs key "Disable Last Change" should be added to map to com.schriftgestaltung.disablesLastChange, and this also should be boolean in the UFO

**Comment by belluzj** [comment]
@anthrotype @moyogo I will add this in #235

**Comment by DavidRaymond** [comment]
@belluzj Thanks for looking at this quickly.  Noticed in your fix, it also needs to covert disablesLastchange to boolean.

**Comment by belluzj** [comment]
Thanks; actually it was included in the fix, because I added the field name to the list of "_CUSTOM_BOOL_PARAMS", but I added a test nonetheless. That's one more test :)

**Comment by DavidRaymond** [comment]
Great - sorry I missed the custom bool params when I looked at the fix.
