### ISSUE TITLE
changelog for release 2.0

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#252]
I usually write a brief changelog for each new releases inside the git annotated tag message. This time the changes since 1.8.0 are many, because we merged the `classtree` branch and refactored most of the modules. And I was only indirectly involved in this, so it's a bit difficult for me to summarize the changes.

Could @moyogo or @belluzj help me write down the most notable changes? I'm not talking about implementation details, but only changes that users of the library would be interested in, like API changes, or bugfixes, etc.

You could write in here the proposed release notes, and then when we're happy I'll use them to cut a new release.

**Comment by belluzj** [comment]
* The lib now supports `.glyphs` -> Python objects -> `.glyphs` round-trip for Glyphs files that were produced with Glyphs >= 2.5b 1076. If some Glyphs data doesn't round-trip, it's a bug. Also, if you edit the Python objects (= instances of `GS*` classes) before writing to `.glyphs`, the diff between the original Glyphs file and the modified one should be minimal and reflect only the changes that were made to the Python objects
* The `glyphsLib.classes` module provides an API that should match the internal API of Glyphs.app. If it doesn't then it's a bug.

**Comment by moyogo** [comment]
That’s a nice to summarize it :-)

**Comment by anthrotype** [comment]
are we ready to release 2.0?
