### ISSUE TITLE
xHeight as string custom parameter crashes defcon

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#268]
Some Noto fonts have a xHeight custom parameter (is that even supported by Glyphs.app itself?).
This used to be cast by glyphsLib to int before setting it in the UFO with defcon.
Now it’s left as a string to match Glyphs.app behaviour when writing *.glyphs file’s.

https://github.com/googlei18n/glyphsLib/pull/227#issuecomment-336103359

But defcon expects an int and chokes with ValueError otherwise
https://github.com/googlei18n/fontmake/issues/369

We need to cast it to int just before passing it on to defcon.
Or if that parameter is not even supported/used by Glyphs, we should ignore it and maybe only keep it in the private lib.

**Comment by moyogo** [comment]
GlyphsApp doesn’t seem to use the xHeight instance customParameter.
When I generate NotoSansArabic-Regular.otf, the OS/2.sxHeight is 374, the same a the master’s xHeight while the xHeight instance customParameter is 536.

**Comment by anthrotype** [comment]
Thanks for checking.
I wonder why MTI added that custom parameter if it's not applied by Glyphs.app...
So what shall we do?
cast to int and apply the xHeight custom parameter in glyphsLib, even though Glyphs.app itself does not?
Or keep that parameter in the lib under com.schrift... but without setting it inthe UFO.info?

**Comment by moyogo** [comment]
@schriftgestalt This seems to be a bug in 2.5b. The GSFontmaster already has a master.xHeight attribute, it doesn’t make sense to have a master.customParameters["xHeight"]. But being able to overwrite the interpolated one with instance.customParameters["xHeight"] may make sense.

**Comment by schriftgestalt** [comment]
> But being able to overwrite the interpolated one with instance.customParameters["xHeight"] may make sense.

Yes. I have a look.

I found why there might be a "xHeight" parameter in the master parameters. It is indeed in the list. But meant for a "local" value like `arabic:123`. That allows different vertical metrics per script. But is only used for displaying the metrics lines in the UI.

**Comment by moyogo** [comment]
Ok, that explains the duplicated ascender and descender for the masters. It would be less confusing with a different name.
