### ISSUE TITLE
differences in master UFOs between 1.8 and master

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#269]
some lib element that previously we didn't write if their value was the same as the default value, are now always being written. I believe they are redundant, only add noise and make serializing/deserializing slower. This is the ones I found but there may be more depending on the source font you check:
- com.schriftgestaltung.Glyphs.Export (default is true)
- com.schriftgestaltung.componentsAlignment (default, ~~I think, is -1~~ EDIT: the default is 0)

Some values used to be written as `int` or `float`, but are now always written as `float` even when the fractional part is 0 (e.g. `1.0` instead of `1`). Probably innocuous but somehow a bit annoying.
fontinfo.plist
- ascender
- capHeight
- descender
- postscriptBlueValues (array)
- postscriptOtherBlues (array)
- xHeight

glif
- advance width and height
- anchor x and y
- component offsets
- point x and y coordinates

Other things that changed for the better are:
- UFO3 background and layers are used instead of private robofont-style layers
- UFO3 guidelines have replaced private robofont-style guidelines
- the GDEF GlyphClassDef contain new entries with uniXXXX names that were previously missing, thanks to https://github.com/googlei18n/glyphsLib/pull/233

**Comment by anthrotype** [comment]
hm... also all the "com.schriftgestaltung.Glyphs.leftMetricsKey" and "com.schriftgestaltung.Glyphs.rightMetricsKey" seem to be gone when exporting UFOs with latest git master. They are exported correctly with stable 1.8.0.

**Comment by anthrotype** [comment]
ok I found where the bug is, fix is coming

**Comment by anthrotype** [comment]
anybody knows why for GSGlyph.{left,right,width}MetricsKey the default is None, whereas for the GSLayer is an empty unicode str `''`?

**Comment by anthrotype** [comment]
I think it would be better to align the two classes' `_defaultsForName`.
I can't try on a mac right now to check if the Glyphs.app python API also has different default values for those metrics keys between GSGlyph and GSLayer.
I would make it None for both rather than emtpy string.

**Comment by moyogo** [comment]
That’s a bug, they should default to None in GSLayer as well.

**Comment by anthrotype** [comment]
ok, thanks. I'll fix that too

**Comment by anthrotype** [comment]
I noticed that the "alignment" attribute for a GSComponent._classesForName is an `int`, whereas in GSGuideLine it is a `str`... why?

**Comment by anthrotype** [comment]
also, previously we were testing if a component had a `disableAlignment` attribute set to True:
https://github.com/googlei18n/glyphsLib/blob/162dc115719d2b0eeeaa3c7ad0576a266d022984/Lib/glyphsLib/builder.py#L786

whereas now we are testing if a component has a `alignment` attribute:
https://github.com/googlei18n/glyphsLib/blob/f3d35ca7cc59fbd2de39255d1a2beb020e432d12/Lib/glyphsLib/builder/glyph.py#L159

what happened to `disableAlignment`? Do they the same thing?
If I grep for `disableAlignment` I can't find anything in latest git master...

**Comment by anthrotype** [comment]
Oh, I already asked the same question :)
https://github.com/googlei18n/glyphsLib/issues/144#issuecomment-284993255

> This is used for the automatic alignment of components. -1 means no alignment and 1 means 'force' alignment for glyphs that would normally not align. This replaced the disableAlignment field. I have updated the spec.

**Comment by schriftgestalt** [comment]
> I can't try on a mac right now to check if the Glyphs.app python API also has different default values for those metrics keys between GSGlyph and GSLayer.

```
print Layer.parent.leftMetricsKey
print Layer.leftMetricsKey
```
gives: 
```
None
None
```

**Comment by schriftgestalt** [comment]
> what happened to disableAlignment? Do they the same thing?

That was changed in the Glyphs API and the file format two years ago.

**Comment by anthrotype** [comment]
are we happy with all the integers in the glyphs file becoming float when exporting to UFOs?
I haven't checked yet where this conversion is taking place. I guess it occurs while loading the GS* classes as those attributes have type float.
I think before with the casting module, there used to be a generic number type that would read either, and would write to the most compact repr.
Not sure what the best solution is here.
