### ISSUE TITLE
why is GSGuideLine.alignment class type a str?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#272]
https://github.com/googlei18n/glyphsLib/blame/f3d35ca7cc59fbd2de39255d1a2beb020e432d12/Lib/glyphsLib/classes.py#L1116

/cc @moyogo

**Comment by schriftgestalt** [comment]
behause it is written as `right` or `center`. (the default is `left` and that is not written).

**Comment by anthrotype** [comment]
I see. Thanks!
