### ISSUE TITLE
move glyphslib.py contents to __init__.py

### ISSUE THREAD

**Issue by behdad** [googlei18n/glyphsLib#3]
Leaving **init**.py empty is a waste of namespace.  glyphslib was supposed to be the name of this module, but that was changed to glyphs2ufo somehow.  No need ot have glyphslib in there (and should have been glyphsLib anyway).

**Comment by jamesgk** [comment]
So, just move glyphslib.py to __init__.py? We can also rename the library to glyphslib. My understanding though was that that would have been the name for a two-way conversion library, but this is really just meant to be Glyphs -> UFO.

**Comment by behdad** [comment]
> So, just move glyphslib.py to __init__.py?

That's what I was thinking.

> We can also rename the library to glyphslib. My understanding though was that that would have been the name for a two-way conversion library, but this is really just meant to be Glyphs -> UFO.

I don't have any strong opinion.  Anyone does?

**Comment by twardoch** [comment]
I'd say, rename the whole package to "glyphsLib" (akin to ufoLib) or "glyphslib" (all lowercase) now, still before it had enjoyed wide proliferation. While it currently only offers .glyphs -> .ufo conversion functionality, it may likely grow in future, and perhaps someone incorporates the reverse functionality. By then, the name "glyphs2ufo" would be too limiting, and changing it more tedious, if other implementations rely on it. 

JvR had named his lib "fontTools" (and ttLib) and only one tool was named "ttx". This was a good decision. Originally, most fontTools usage was indeed limited to using the ttx tool and the .ttx format, but today, direct usage of fontTools.ttLib is much more popular, and the lib has grown to include other tools beyond just ttx.

**Comment by twardoch** [comment]
Alternatively, rename the package to glyphsTools, the main lib inside to glyphsLib, and the commandline tool to glyphs2ufo. That would broadly mimic the fontTools/ttLib/ttx structure. In future, other tools such as ufo2glyphs or glyphs2gx or glyphssubset or whatever else could be added there.

**Comment by jamesgk** [comment]
Sorry for holding this off. Is it too late to change the library name? Do we want glyphs2ufo to be a package within glyphsLib? I personally think glyphsTools at the top level is overkill, though.

**Comment by behdad** [comment]
I don't have a strong opinion about this.

**Comment by schriftgestalt** [comment]
To call the module 'glyphslib' will give it more room to house others things. 
The the 'glyphs2ufo' could be on of several output components, like 'glyphslib.writers.ufo'. There should be a 'writer.glyphs'. This would allow the use of the library to manipulate .glyphs files from scripts outside of Glyphs similar to robofab.

**Comment by davelab6** [comment]
I'm in favor of a writer.glyphs for  TruFont :)

I dont think it's too late to change it

**Comment by jamesgk** [comment]
OK, so we can have a structure like

```
glyphsLib
  writers
    ufo (provides: "build_ufos_from_data")
    glyphs (TODO: "build_source_from_data")
  readers
    glyphs ("load_data_from_source")
    ufo (TODO: "load_data_from_ufos")
```

or

```
glyphsLib
  glyphs2ufo ("load_data_from_source", "build_ufos_from_data")
  ufo2glyphs (TODO: "load_data_from_ufos", "build_source_from_data")
```

Any strong preferences?

**Comment by davelab6** [comment]
In the first case, would a ufo2ufo then be possible, which could be useful
as another normalizer?

**Comment by davelab6** [comment]
(And similarly a glyphs2glyphs normaliser)

**Comment by jamesgk** [comment]
Well sure, either way it should be possible to round trip from glyphs source / ufo -> glyphs data -> glyphs source / ufo, provided we filled in the todos.

**Comment by schriftgestalt** [comment]
The first option seems clearer to me. Because then there can be something in the middle that does something with the data. Or someone else adds another loader or writer?

**Comment by davelab6** [comment]
Right, like XFO

**Comment by schriftgestalt** [comment]
Then we need to define a intermediate data format. ;)

**Comment by brawer** [comment]
Closing this bug because the initial topic (“ move glyphslib.py contents to __init__.py”) appears to be done. Feel free to file new bugs any time...
