### ISSUE TITLE
build_style_name no longer strips Regular off of Condensed

### ISSUE THREAD

**Issue by punchcutter** [googlei18n/glyphsLib#300]
fontmake now fails with MTI sources because `glyphsLib/builder/names/build_style_name()` no longer strips "Regular" from names like "NotoSansKhmer-Condensed". Now that gets written out to UFO as "NotoSansKhmer-CondensedRegular" and that key doesn't exist in the MTI plist. 

The old way for `build_style_name` was
```
if (italic or width or custom) and weight == 'Regular':
    weight = ''
```
but the new way doesn't remove "Regular":
```
    return ' '.join(
        s for s in (custom, width, weight, 'Italic' if is_italic else '') if s
    ) or 'Regular'
```
Is there a reason to keep Regular in the name? If so we need to update all the MTI plist files to expect the new name. If not we need to change this back to drop "Regular" like it used to.

**Comment by anthrotype** [comment]
Looks like a regression. @belluzj could you pls take a look?

**Comment by punchcutter** [comment]
The change was introduced with https://github.com/googlei18n/glyphsLib/commit/ce3d4e96fb56882705bcb1b876414c89fae8e644

**Comment by anthrotype** [comment]
hmm, that's strange. We explicitly have a test for that:
https://github.com/googlei18n/glyphsLib/blob/901507ebaad5e0e46e6eddb3d9bce3ce42342206/tests/builder_test.py#L70 

I'll try to build NotoSans-Khmer with latest versions of the toolchain and report back here

**Comment by anthrotype** [comment]
it turns out, the problem isn't in the `build_style_name` itself, but in the caller `to_ufo_names` that is passing "Regular" as the weight. Whereas for the width argument, the "Regular" value is special-cased, it wasn't the case for the weight.

Still not clear to me when this regression was introduced. Anyway, the fix is trivial and is coming soon
