### ISSUE TITLE
designspace output path should be configurable

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#325]
currently it's generated from the font's familyName and the "base" style (i.e. shared by all masters):

https://github.com/googlei18n/glyphsLib/blob/0a86327a93b3f324f200e35a23f639db4ae58280/Lib/glyphsLib/builder/builders.py#L204-L210

**Comment by anthrotype** [comment]
this new `designspace_path` option (a full path, not just the basename relative to the masters directory) should trickle down from the `build_masters` function, to the `to_designspace` function and cached in the `UFOBuilder` constructor, to be set on the designspace object returned by the `UFOBuilder.designspace` getter.

**Comment by belluzj** [comment]
Why do you want such an option? I think the final path in which you want to store the designspace is not relevant in the builder, because you can set it afterwards when you have the DesignspaceDocument instance, and do that only if you want to save to the disk.

What is your use-case?

**Comment by anthrotype** [comment]
> I think the final path in which you want to store the designspace is not relevant in the builder, because you can set it afterwards when you have the DesignspaceDocument instance, and do that only if you want to save to the disk.

right, but currently fontmake uses `glyphsLib.build_masters` which will save the designspace to disk and return a predefined `designspace_path`.

https://github.com/googlei18n/fontmake/blob/aa412a101e4258c4e6da21c95556607ae03df8ec/Lib/fontmake/font_project.py#L69-L71

**Comment by anthrotype** [comment]
> What is your use-case?

the use case is being able to specify on the fontmake command line the exact output designspace path, instead of it being autogenerated. (e.g. a build system can create rules with clearly specified input and outputs)

**Comment by anthrotype** [comment]
I could change fontmake to stop using `glypshLib.build_masters` and call `glyphsLib.builder.to_designspace` (or some higher level function, `glyphsLib.build_designspace`, that takes a path to glyphs source, parses it to GSFont and passes it on to the builder) and then decide itself where to save the designspace object.
WDYT?

**Comment by belluzj** [comment]
In general I think that with those two functions:
* `GSFont(path) -> GSFont`
* `to_designspace(GSFont) ->DesignspaceDocument`

the "clients" of glyphsLib such as fontmake have a high-level enough API, and that glyphsLib should not provide more `build_designspace`/`load_to_designspace` functions, because they don't have much added value (to my eyes).

What are your arguments in favor of such functions? Maybe it's better for a python package to provide one entrypoint that does everything rather that several more atomic APIs that the user has to combine themselves?

**Comment by anthrotype** [comment]
yes, let's get rid of all the stuff we don't use anymore and bump major number. 

I just would like to have the top level API (the `__all__` of the `glyphsLib.__init__` module) be the one that clients are recommended to use, instead of them having to reach in the internals as in `glyphsLib.builder.to_designspace`.

**Comment by belluzj** [comment]
Yes, and actually I have imported `to_designspace` in `glyphsLib.__init__`, and that's how I use it in tests:

```python
from glyhsLib import to_designspace
```

I guess it just needs to be added to `__all__` as well?

**Comment by anthrotype** [comment]
> I think the final path in which you want to store the designspace is not relevant in the builder

maybe it relevant, in the end, see https://github.com/googlei18n/glyphsLib/commit/5c318ba61378ee955ceb97314d26f87e29b1b061#r28240226

if all these "filename" attributes are indeed all relative to the root path of the designspace document, then we can't write them out properly if we don't know the final path where this document is going to be saved.  :thinking:

**Comment by belluzj** [comment]
I think Erik might have had a solution in mind for this kind of situation because his original Designspace code is very careful with paths:

https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/designspaceLib/__init__.py#L1095
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/designspaceLib/__init__.py#L1171

@letterror Maybe something like: "set the instance paths and their filenames will be updated automatically when the document is written somewhere"?

**Comment by anthrotype** [comment]
maybe this `filename` attributes should really be properties that are computed based on the document path (if any) upon writing. I don't like that there are two ways to set the masters/instances paths (i.e. the `path` and the `filename` attributes).

Also, I believe _some_ path must be required otherwise these descriptors are useless, as they don't refer to anything.
cf https://github.com/fonttools/fonttools/issues/1219

**Comment by schriftgestalt** [comment]
When I tried to use the designspace writer from within Glyphs, I took me some time to figure out where the files actually would go. Because in this case, the current directly is not set to something meaningful as when run from the command line.

**Comment by LettError** [comment]
@anthrotype The paths stored in the document are relative so that the ufos can be generated in different places. The `sourceDescriptor.path` attribute is the absolute path to the ufo on the local system. The `sourceDescriptor.filename` attribute is the original path as found in the document.

The conditions described in https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/designspaceLib/__init__.py#L1095 are based on actual use cases.

It should be possible to read the designspace, make some edits and save it again without the paths changing or being recalculated.

**Comment by anthrotype** [comment]
relative to the directory of the designspace itself, yes, but the problem is we don't know that yet because we are not reading a designspace, but creating one from scratch

**Comment by LettError** [comment]
So you don't intend to write the designspace at all? Or you don't know where the fonts are when you're building it?

**Comment by anthrotype** [comment]
one library (glyphsLib) is creating a designspace from scratch without knowing where another application (fontmake) will decide where to write the file out to disk. Also, the library creating the designspace (glyphsLib) doesn't know where the fonts are because it only holds them in memory without saving them to disk (the `font` attributes that Jany added to source or instance descriptors in designspaceLib).

**Comment by LettError** [comment]
I don't know if it is something the designspace can solve then?

**Comment by anthrotype** [comment]
Or one may argue that an API that creates designspace documents like glyphsLib's is not complete if it doesn't also write that document to a file on the filesystem, because all the relative filename references inside the document require it to be located somewhere.
If that's the case, then the function that creates the designspace needs:
1) the output path for the designspace file
2) the directory where to save the master sources
3) the directory where to save the instances

**Comment by behdad** [comment]
> Or one may argue that an API that creates designspace documents like glyphsLib's is not complete if it doesn't also write that document to a file on the filesystem, because all the relative filename references inside the document require it to be located somewhere.

Or glyphsLib can just set .font items, then you can call some other function on the designspace document to set the path / directory, whatever, before writing.

**Comment by anthrotype** [comment]
in https://github.com/googlei18n/fontmake/pull/410, I ended up calling `glyphsLib.to_designspace` and then saving the designspace to the desired user-defined location, so I no longer need to modify `glyphsLib.build_masters` any more.

We may close this.. or we may keep it open to discuss what to do with those `build_masters` and `build_instances` functions, and also the glyphs2ufo script itself. Is the latter still needed given that one can simply use fontmake [-i] -o ufo` to accomplish the same thing?
and what about the accompanying ufo2glyphs? Shouldn't there be one at least for consistency?

**Comment by moyogo** [comment]
I don't think we need glyphs2ufo anymore. We should add `-o glyphs` to fontmake. I guess build_masters and build_instances can be deprecated.

If we can we should also drop the `-g`, `-m`, etc. from fontmake and just figure out the input type.
