### ISSUE TITLE
Instantiating a GSFont object with StringIO

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/glyphsLib#328]
I see this object must use a path in order to work.

```
Traceback (most recent call last):
  File "families_src_type.py", line 140, in <module>
    get_glyph_axis("https://raw.githubusercontent.com/m4rc1e/Pacifico/master/sources/Pacifico.glyphs")
  File "families_src_type.py", line 112, in get_glyph_axis
    font = GSFont(glyphs_file)
  File "/Users/marc/Documents/googlefonts/research/potential_variable_families/env/lib/python2.7/site-packages/glyphsLib/classes.py", line 3007, in __init__
    "Please supply a file path"
AssertionError: Please supply a file path

```

 https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/classes.py#L3005-L3016.

I'm more than happy to implement this if people want. Its useful to me because I often download .glyphs files using requests via the github api. I don't want to store them on my system, I just need to inspect them.

**Comment by moyogo** [comment]
This is already implement with `glyphsLib.loads()`. See https://github.com/googlei18n/glyphsLib/issues/327

**Comment by m4rc1e** [comment]
@moyogo Thank you!
