### ISSUE TITLE
Arabic mark positioning

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/glyphsLib#33]
The file [NotoSansArabic-MM.glyphs](https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs) from noto-source outputs the following TTF in glyphs:

[NotoSansArabic-Regular.ttf.zip](https://github.com/googlei18n/glyphs2ufo/files/215753/NotoSansArabic-Regular.ttf.zip)

With this TTF it is possible to see that mark U+064B (arabic fathatan) has a positioning rule with base U+FEC0 (arabic letter dad medial form):

```
$ hb-shape NotoSansArabic-Regular.ttf "ﻀً"
[uni064B=0@490,114+0|uniFEC0=0+949]
```

This is despite the fact that in Glyphs' UFO output, glyph U+FEC0 does not have any anchors:

[dad-ar.medi.glif.zip](https://github.com/googlei18n/glyphs2ufo/files/215755/dad-ar.medi.glif.zip)

@schriftgestalt, how is the mark positioning rule determined in this case? Does the output UFO contain the necessary information to produce a correct TTF?

**Comment by schriftgestalt** [comment]
Anchors are taken from the components.

**Comment by jamesgk** [comment]
OK. I think at least for glyphs2ufo that we want to propagate those components' anchors to the parent glyph, since this behavior seems to be Glyphs-specific.

**Comment by behdad** [comment]
Agreed.

On Wed, Apr 13, 2016 at 11:42 AM, James Godfrey-Kittle <
notifications@github.com> wrote:

> OK. I think at least for glyphs2ufo that we want to propagate those
> components' anchors to the parent glyph, since this behavior seems to be
> Glyphs-specific.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/glyphs2ufo/issues/33#issuecomment-209589270>
>



-- 
behdad
http://behdad.org/

**Comment by jamesgk** [comment]
I think we need to revisit this, because propagating anchors from the first component of every glyph doesn't seem to always work. For example with [NotoSansHebrew-MM.glyphs](https://raw.githubusercontent.com/googlei18n/noto-source/master/src/NotoSansHebrew-MM.glyphs) the glyph yodyod-hb has two yod-hb components, but in the output from Glyphs it doesn't have any mark attachments.

My best guess for what to do is to propagate anchors from a "base" component only if exactly one exists, where base component is defined as one which doesn't have any mark anchors and probably hasn't been attached via an anchor.

**Comment by behdad** [comment]
Might as well open a new issue...

So, remind me, how is it decided where each of the yod-hb's connect to?

**Comment by jamesgk** [comment]
> Might as well open a new issue...

I think this is the same issue, the existing solution just isn't sufficient

> So, remind me, how is it decided where each of the yod-hb's connect to?

In this specific case, no idea. All we have in the Glyphs source is two components, one with an offset. Sometimes though (not in this case) the component glyph has mark anchors e.g. _top, _bottom which provide clues as to how they may have been attached by the source author.

**Comment by schriftgestalt** [comment]
In the case of the 'yodyod-hb', it should (I’ll put it on my list) produce liga to mark code from the anchors in the yod-hb. To prevent this, one would need to change the subcategory of the yodyod-hb to 'Other'.

**Comment by jamesgk** [comment]
Should be fixed.
