### ISSUE TITLE
float written un-quoted, loading back the file raises ValueError

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#337]
Take this file:
https://raw.githubusercontent.com/googlei18n/noto-source/master/src/NotoSansCanadianAboriginal/NotoSansCanadianAboriginal-MM.glyphs

Load it with glyphsLib, save it back to file with no modifications, and try to re-load the new copy.
A ValueError is raised while attempting to parse some unquoted float numbers in a userData dictionary, that in the original font were wrapped in quotes:

```python
>>> from glyphsLib import GSFont
>>> f1 = GSFont("src/NotoSansCanadianAboriginal/NotoSansCanadianAboriginal-MM.glyphs")
>>> f1.save("src/NotoSansCanadianAboriginal/NotoSansCanadianAboriginal-MM_2.glyphs")
>>> f2 = GSFont("src/NotoSansCanadianAboriginal/NotoSansCanadianAboriginal-MM_2.glyphs")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/classes.py", line 3013, in __init__
    p.parse_into_object(self, fp.read())
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 65, in parse_into_object
    i = self._parse_dict_into_object(res, text, 1)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 175, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 203, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 156, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 175, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 156, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 175, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/clupo/Github/glyphsLib/Lib/glyphsLib/parser.py", line 132, in _parse
    value = self.current_type(value)
ValueError: invalid literal for int() with base 10: '22.0'
```

diffing the original font with the dumped font, reveals:

```diff
@@ -893,7 +893,7 @@
 GSOffsetVertical = 3;
 noodleExtremesAndInflections = 1;
 noodleRemoveOverlap = 1;
-noodleThickness = "22.0";
+noodleThickness = 22.0;
 };
 verticalStems = (
 26,
@@ -981,7 +981,7 @@
 userData = {
 noodleExtremesAndInflections = 1;
 noodleRemoveOverlap = 0;
-noodleThickness = "190.0";
+noodleThickness = 190.0;
 };
 verticalStems = (
 78,
@@ -1068,7 +1068,7 @@
 userData = {
 noodleExtremesAndInflections = 1;
 noodleRemoveOverlap = 1;
-noodleThickness = "84.0";
+noodleThickness = 84.0;
 };
 verticalStems = (
 146,
@@ -1157,7 +1157,7 @@
 GSOffsetVertical = 1;
 noodleExtremesAndInflections = 1;
 noodleRemoveOverlap = 0;
-noodleThickness = "106.0";
+noodleThickness = 106.0;
 };
 verticalStems = (
 193,
```

**Comment by anthrotype** [comment]
pushed this https://github.com/googlei18n/glyphsLib/commit/cb20a4a19b3029248669fa09fdb0351b83a4ffba, which brakes `tests/writer_test.py::WriterRoundtripTest::test_roundtrip_on_file`

**Comment by anthrotype** [comment]
I think the problem is in the parser:
https://github.com/googlei18n/glyphsLib/blob/cb20a4a19b3029248669fa09fdb0351b83a4ffba/Lib/glyphsLib/parser.py#L79-L83

the string "22.0" can be parsed into a float, and it will return True to the `is_integer` call, so the current_type is set to `int`, which will fail with ValueError because `int("22.0")` is not valid integer.
When is_integer returns True, we should drop anything after the "." and then interpret it as integer.

**Comment by madig** [comment]
Upon putting `userData = { noodleThickness = 1.0; }` into a Glyphs file, doing `print(type(Glyphs.font.userData["noodleThickness"]))` will print `objc._pythonify.OC_PythonInt`. So floats without a decimal part are turned into ints. Will implement your suggestion.

**Comment by anthrotype** [comment]
> floats without a decimal part are turned into ints

right, because that's what they really are (see is_integer()).
But when Glyphs.app writes that userData containing a python float to a file, does it quote it all the time?

**Comment by schriftgestalt** [comment]
Normally it should not quote this but for user data it can happen. Internally, that is not a problem as getting something from a collection class like a dict or array is an object and to get to the float or int, you need to get the `floatValue` or `intValue` and both, NSNumber and NSString have those methods.

To keep the data types as stable as possible, Glyphs doesn't try to guess the content of strings. When reading a file, if it is a string that looks like a float `"22.0"`, it will keep it as a string. On writing, it will such a string will get quotes to not get a float the next time the value is read.
