### ISSUE TITLE
build_masters builds designspace file that contains only three axes

### ISSUE THREAD

**Issue by RafalBuchner** [googlei18n/glyphsLib#356]
In .glyphs file, I defined a weight axis (as a custom parameter). For test reason, I also created my own, with a silly name "Lalala" (tagged as 'lala'). I've tryied to export it with the following code:

```python
from glyphsLib import build_masters

font = "MyFont.glyphs"
master_dir = 'master_ufos'
designSpace_dir = "."
ufos = build_masters(font, master_dir,designSpace_dir)
```

Even when I defined a design space of my typefamily with only two axes, my exported designspace file contained three axes: "custom","width","weight". I've got a filling, that those values are connected to the old way of dealing with design space issues in glyphsapp, where the user could work only with 3 predefined axes named the same. What's  more: those axes had some strange max and min values.

**Comment by madig** [comment]
Have you tried this with git master? Please attach your example glyphs file.

**Comment by anthrotype** [comment]
The Axes custom parameter should be supported once we cut a new release of glyphsLib.
Basically, we only need to draft the changelog (#351).
