### ISSUE TITLE
Behave correctly when the input UFOs provide non-unique fontMasterID

### ISSUE THREAD

**Issue by belluzj** [googlei18n/glyphsLib#400]
**Use-case**:
* user draws Light and Bold in Glyphs
* converts to UFOs
* interpolates a Regular using e.g. FontLab
* converts back to Glyphs

**Problem**: if the interpolated Regular copies `lib` data from e.g. the Light, then it will probably get a duplicate value for `com.schriftgestaltung.fontMasterID`. When converting to Glyphs, glyphsLib will freak out and paste all the outlines in the same master/drop outlines...

**Expected outcome**: glyphsLib should check that all UFOs come with different values for `com.schriftgestaltung.fontMasterID` and if there are duplicates, throw or ignore those values.

Maybe the same problem could happen for layer ids as well?

*Note: why we store the fontMasterID in the UFOs:*
1. it supports a workflow where your main source is glyphs, and you want to do a small change using a UFO-only editor. When you go back to glyphs, the internal IDs are preserved and the git diffs should be more representative of what you actually changed in the UFO editor
2. it allows for a 1-to-1 roundtrip (glyphs->UFOs->glyphs) which makes it easy to spot whether glyphsLib loses some information from the glyphs file

**Comment by madig** [comment]
So this has apparently also happened when working in Glyphs.app now. I suppose we can raise an exception when we find a duplicate fontMasterID.

**Comment by anthrotype** [comment]
Sgtm

**Comment by schriftgestalt** [comment]
What do you mean by it happens in Glyphs. What exactly did you do?

**Comment by madig** [comment]
I didn't do anything :O gonna ask the designer next week whether he remembers anything.

**Comment by madig** [comment]
I was just told that it actually didn't happen in Glyphs but elsewhere, woops.
