### ISSUE TITLE
Glyphs deletes UFO data on save

### ISSUE THREAD

**Issue by madig** [googlei18n/glyphsLib#404]
A design team found that the hinting code in UFO/data/ containing ttx dumps and saved as a custom parameter I think is tossed by Glyphs on saving. Investigate.

**Comment by schriftgestalt** [comment]
do you have some sample data?

**Comment by madig** [comment]
Here: [test.zip](https://github.com/googlei18n/glyphsLib/files/2357766/test.zip)

TSI3 gets lost in 2.4.4, but it doesn't happen in 2.5.1.

**Comment by schriftgestalt** [comment]
The current version is keeping all the data. There are two issues in the file. It uses CRLF line endings and has some empty background entries. Glyphs is omitting them.

**Comment by madig** [comment]
Closing for now as a possible Hex/Base64 encoding issue that seems to have been resolved.
