### ISSUE TITLE
Fix test failures for XML comparisons

### ISSUE THREAD

**Issue by Kelledin** [googlei18n/glyphsLib#475]
When running tests on the 3.1.4 release, I'm noticing several test failures, all of them having to do with harmless differences in Designspace XML generation: extra whitespace (such as different indentation), reordered attributes, and minor uppercase/lowercase differences (like 'encoding="UTF-8"' vs 'encoding="utf-8"' in the XML declaration).  Upon human examination, the generated XML output looks functionally identical to the expected output, but the tests are obviously just doing a flat text comparison.

I'd suggest we switch the affected tests to use an XML-specific comparison tool instead?  I've been able to adapt these tests to use xmldiff (https://pypi.org/project/xmldiff/) with fairly minor modifications.  Based on my observations, xmldiff in default mode responds to certain cases as follows:

- Harmless whitespace differences are ignored (good)
- XML declaration "encoding" value is treated as case-insensitive (good)
- Other tag names, attribute names, and attribute values are treated as case-sensitive (good)
- Functional alteration of any tag, attribute name, or attribute value is flagged (good)
- Adding or removing tags or attributes is flagged (good)
- Changing text content within a container is flagged (good)
- Reordering attributes within a tag is ignored (good)
- Reordering same-name tags within the same scope is flagged (good)
- Reordering unique-name tags within the same scope is flagged (probably OK)
- Adding XML comments is flagged (eeeeh...tolerable; doesn't hurt us at the moment)
- Switching single vs. double quotes on attribute values is ignored (good)
- Common XML syntax errors are flagged (good)

Overall, for me, xmldiff is smart enough about comparison to get tests to a solid pass.

The output on test failure is necessarily different; instead of common diff output, differences are itemized and reported in an XPATH-like syntax (IMHO this is probably better for XML, but people used to diff output might not appreciate it).

If we're OK with a change like this, I'll open a PR and sign on to the contributor agreement.

**Comment by anthrotype** [comment]
the diffs you see when running the tests locally are the result changes in upstream fontTools (specifically ufoLib and designspaceLib) in the way it writes out xml and plist files. They are harmless. 
This CI faiulres are probably connected https://github.com/googlei18n/glyphsLib/pull/473

honestly to keep things simple I'd prefer not to use xmldiff but just update the expected test data and bump the minimum required fonttools to a more recent version that has those XML changes.
Would you like to contribute a patch in this direction instead?

**Comment by anthrotype** [comment]
Oh and thanks for your interest in glyphsLib :)

**Comment by Kelledin** [comment]
We could....but that seems like we're deliberately stuck on a treadmill, updating the test data over and over again for harmless changes.

As it is, the practical changes for xmldiff are pretty miniscule.  I'll post a PR shortly just for everyone to see what it entails.

**Comment by anthrotype** [comment]
ok

**Comment by schriftgestalt** [comment]
Sometimes it is good to have tests that check for sourcecode changes to be notifyed to avoid superficial git noise.

**Comment by anthrotype** [comment]
Fixed by #476
