### ISSUE TITLE
Switch export flag over to public.skipExportGlyphs

### ISSUE THREAD

**Issue by madig** [googlei18n/glyphsLib#515]
Depends on the next ufo2ft version.

**Comment by madig** [comment]
@schriftgestalt Can you please add support for this in your UFO reader/writer? http://unifiedfontobject.org/versions/ufo3/lib.plist/#publicskipexportglyphs

The idea is basically `ufo.lib["public.skipExportGlyphs"] = sorted(set(glyph.name for glyph in font if glyph.export is False))`

**Comment by madig** [comment]
I'm looking at the code in glyphsLib. Support both the per-glyph lib key _and_ the new `public.skipExportGlyphs`? Reading a UFO should recognize the old per-glyph lib key at least and convert to the new list, but dropping the per-glyph key makes opening UFOs in Glyphs.app not work until support is added and people upgraded. Hm.

**Comment by schriftgestalt** [comment]
I don’t think that is a good idea. the export state is a glyph level property and should be stored on that level. With that logic, we need to put the Unicode in the designspace, too.

**Comment by anthrotype** [comment]
https://github.com/unified-font-object/ufo-spec/issues/77

**Comment by madig** [comment]
@schriftgestalt I, too, would be in favor of a UFO4 format that unifies Designspace and UFO concepts, but  that's some wazs off still I think. Making it a separate lists certainly makes extracting the list easier :)

**Comment by madig** [comment]
I have decided to read the glyph-level lib key `com.schriftgestaltung.Glyphs.Export` for round-tripping but not write it.

**Comment by madig** [comment]
In master.

**Comment by madig** [comment]
The custom parameters manipulating glyph export are not handled: https://github.com/googlei18n/glyphsLib/pull/519#issuecomment-481641521.
