### ISSUE TITLE
Blue zones

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#6]
As far as I understand the blue zones are not handled correctly. All 'negative' zones (except the one at the baseline) need to go to the other zones, not only the ones that are below the baseline.

**Comment by jamesgk** [comment]
Could you give an example of where glyphsLib handles these incorrectly? I just tried to produce the same results as Glyphs, and I'm having a hard time finding documentation on these values.

**Comment by schriftgestalt** [comment]
I can’t remember what file I tried. It would probably have a bottom zone for superior figures. With a pos like 400 and size -15.
