### ISSUE TITLE
Glyphs handles source in unexpected way

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/glyphsLib#64]
@schriftgestalt, we noticed something strange recently: in [NotoSansArabic-MM.glyphs](https://raw.githubusercontent.com/googlei18n/noto-source/master/src/NotoSansArabic-MM.glyphs), the Light layer of the glyph "fehDotbelowThreedotsabove-ar" contains a component with name "threedotsupabove-ar" and transform {1, 0, 0, 1, -353, 18}. Despite this negative x-offset, when the file is opened in Glyphs the component is said to have offset 620, 18. Exported UFOs or TTFs have the values reflected in the UI (x=620).

Why this discrepancy? My best guess is that Glyphs is ignoring the transform and attaching the component to an anchor. But this would make it harder to read the source file.

**Comment by jamesgk** [comment]
cc @adrientetar @behdad

**Comment by schriftgestalt** [comment]
It seems that the file was saved in a version where the automatic alignment was not working correctly. Because the marks/dots are totally wrong in the file and are automatically "repaired" when you open the file.

The transformation of the components is only used if the component is set to not align or the alignment it disabled on font level.

**Comment by jamesgk** [comment]
I see, thanks. So I guess the way to fix this particular issue is just to open and re-save in Glyphs.

Still, maybe our handling of components in glyphsLib is incorrect; I don't think we're taking alignment into consideration.

**Comment by m4rc1e** [comment]
Hey @jamesgk,

I've also noticed smart components in Glyphs don't work either. You probably already know about this ;)

**Comment by schriftgestalt** [comment]
The automatic alignment is not needed in glyphsLib. The transform struct should be enough. For aligned components, it is saved just to be able to use it externally like in glyphsLib.

The smart components are a different issue.

**Comment by jamesgk** [comment]
OK, great to know.

@m4rc1e let's definitely open a separate issue for smart components.

**Comment by behdad** [comment]
@schriftgestalt What version of Glyphs is required to save these correctly?
@marekjez86 We need to ask Monotype to use a version of Glyphs that fixes this issue.

**Comment by behdad** [comment]
Reopening to conclude on a resolution.
James: maybe we should warn if the Glyphs version the file was saved with is too old?

**Comment by behdad** [comment]
I don't like silently generating bad fonts.

**Comment by schriftgestalt** [comment]
I’m not really sure what is the earliest version that would fix this. But version 2.3 and later works fine.
For some time now, glyphs saves its version into the beginning of the file. Files without that "_appversion" entry should be considered outdated.

I updated the file and send a pul request.

**Comment by marekjez86** [comment]
@behdad : per https://glyphsapp.com/blog/new-features-in-glyphs-2-3 2.3 was released around 2016 May 10. The NotoSansArabic-MM.glyphs source was delivered to us on 2016 February 1 (i.e., before this fix was avaialble - let's just assume it; something like this will happen in the future). I do not think there's anything I can communicate to MTI. If there are bug fixes like this in the Glyphs.app then we need a policy that somehow auto-matically/-magically opens all the sources and saves them. We also need a process to support it (including running the pipeline and a QA process to validate the fonts). Maybe this (opening the sources in the glyphs.app and re-saving the output) should be an optional step in the pipeline? ... but I imagine licensing issues ...

**Comment by schriftgestalt** [comment]
I don't think that there need to be an automatic system to fix this kind of things. This is an ordinary bug in the source that should have been recognized before submitting and should be fixed manually.

**Comment by schriftgestalt** [comment]
I had another look at the file. In around 600 glyphs, some masters (mostly the condensed) have disabled the alignment. That leads to inconsistent spacing and mark/dot positions. 

To display all affected glyphs, set up a list filter like this:
<img width="500" alt="screenshot" src="https://cloud.githubusercontent.com/assets/174660/17364407/4f5c3184-5980-11e6-8092-3d9495ad89f3.png">
