### ISSUE TITLE
Wrong import of Kerning groups

### ISSUE THREAD

**Issue by impallari** [googlei18n/glyphsLib#71]
Sometimes the "Kering Classes" from the UFO files end up as "Opentype Classes" in the exported Glyph file. These is wrong.
See attached image: Empty kerning groups in the columns, and kerning classes wrongly imported as opentype classes
![screen shot 2016-08-18 at 19 47 40](https://cloud.githubusercontent.com/assets/3036973/17793459/d14ae092-657d-11e6-9492-2d2422c1f13d.png)

Instead, they should end up being "Kerning Groups", as displayed in the next image:
Note that the groups columns are now filled, and the opentype classes where removed.
![screen shot 2016-08-18 at 19 50 48](https://cloud.githubusercontent.com/assets/3036973/17793507/352071ea-657e-11e6-9f57-770472764014.png)

**Comment by schriftgestalt** [comment]
Can you send me the ufo?
Georg

**Comment by impallari** [comment]
The source and converted files are here: https://github.com/m4rc1e/Raleway

**Comment by schriftgestalt** [comment]
The .ufos in the Raleway/old/version-3.000/src/ folder contain FontLab style kerning. That is not supported in Glyphs and probably nowhere else, too.

**Comment by brawer** [comment]
From a coarse glance it looks like this bug can be closed. If anyone disagrees, feel free to re-open it.
