### ISSUE TITLE
Shifted diacritics

### ISSUE THREAD

**Issue by impallari** [googlei18n/glyphsLib#72]
Diacritics jumps all over the place in exported versions.
See attached animation: Original vs Migrated
![diacritics original vs migration - animation](https://cloud.githubusercontent.com/assets/3036973/17798893/1ac5dd34-65ac-11e6-82b8-1a75d303d267.gif)

**Comment by impallari** [comment]
The source and converted files are here: https://github.com/m4rc1e/Raleway

**Comment by jamesgk** [comment]
What exactly are we looking at here? What is "Original" vs. "Migrated"?

**Comment by adrientetar** [comment]
It would seem original is Glyph and migration is fontmake (has incorrect placement for certain diacritics).

**Comment by khaledhosny** [comment]
I think the original is FontLab and migrated is Glyphs, so glyphsLib is not involved at all.

**Comment by moyogo** [comment]
Basically this issue and #71 have nothing to do with glyphsLib.
@impallari glyphsLib is a library which “provides a bridge from Glyphs source files (.glyphs) to UFOs via defcon” but it it not used by Glyphs.

Although @schriftgestalt is involved, opening issues about Glyphs.app here is inappropriate. If I’m not wrong, it’s better to either report the issue on https://forum.glyphsapp.com/ or email @schriftgestalt directly.

**Comment by impallari** [comment]
Yep, you are all right, sorry.
Initially I thought that the source had been converted using glyphsLib but later learned is was done using the FL export macro. Sorry.

**Comment by jamesgk** [comment]
No problem. Thanks for confirming!
