### ISSUE TITLE
Take ascender/descender values from master data when not found in instances?

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/glyphsLib#78]
I noticed that Glyphs will use ascender and descender values from font masters when not defined in instances. I'm not entirely sure how this works -- it doesn't seem to interpolate, so perhaps it just takes values from the Regular master or something.

Anyways, maybe this should also happen when generating instance UFOs.

**Comment by schriftgestalt** [comment]
Glyphs does interpolate the values from all involved font masters. if you have a file where it don't work, please send it to me that I can fix it.

**Comment by jamesgk** [comment]
Thanks Georg. Upon further investigation I see that I was at least partially mistaken. But, attached is an example source with unexpected output. In this case, I have two masters with weight values 60 and 100 and ascender values 600 and 800. I have two instances with weight values 60 and 80. In the instance output I see expected sTypoAscender values (600 and 700), but hhea ascent and usWinAscent seem to be 1000 for both instances. Not sure what's going on there:

[test.glyphs.zip](https://github.com/googlei18n/glyphsLib/files/556785/test.glyphs.zip)

In any case, it seems to me that we do indeed want to interpolate, and in fact I think that's what we're already doing via MutatorMath. So I think the bug is on ufo2ft. When compiling the UFOs, we need to use the interpolated ascender and descender values.

**Comment by jamesgk** [comment]
Opened https://github.com/googlei18n/ufo2ft/issues/78 on ufo2ft.

**Comment by schriftgestalt** [comment]
To ensure equal line spacing all three sets of vertical metrics use the same numbers. The ascender is calculated UPM * 1.2 - descender. And as most (double) accents are above the letters, all extra space is added on top.

If I would base the line spacing on the sum of ascender + descender, it could give difference line spacing between different weights. 

There are probably better ways to calculate the numbers but that approach worked quite well so far.

**Comment by jamesgk** [comment]
For [Noto Serif Sinhala](https://github.com/googlei18n/noto-source/blob/master/src/NotoSerifSinhala/NotoSerifSinhala-MM.glyphs), I noticed that all the master ascender values are 997, and all of the output instances have this value for hhea ascent, usWinAscent and usWinAscent. Am I right in thinking that this is a special case -- when all the masters contain the same ascender value, that ascender value is used instead of UPM * 1.2 - descender?

**Comment by schriftgestalt** [comment]
The calculation is only true, if ascender + descender < UPM * 1.2. 
So it is calculated like this: 
```
typoLineGap = UPM * 1.2 - typoAscender - typoDescender 
winAscender = typoAscender + typoLineGap
winDescender = typoDescender
hheaAscent = winAscender
hheaDescent = winDescender 
```

**Comment by schriftgestalt** [comment]
Of cause the lineGap can’t be negative and is set to zero in that case.

**Comment by jamesgk** [comment]
So, is `hheaLineGap` calculated as `UPM * 1.2 - hheaAscent - hheaDescent`? I.e. always zero?

**Comment by schriftgestalt** [comment]
No, only if `ascender + descender < UPM * 1.2`

**Comment by jamesgk** [comment]
Sorry, I guess what I was wondering was, is it

`hheaLineGap = max(UPM * 1.2 - hheaAscent - hheaDescent, 0)` (which incidentally is always 0),

or simply

`hheaLineGap = typoLineGap`.

Sounds like the latter if it's dependent on the generic ascender and descender values.

**Comment by jamesgk** [comment]
Although, that's *not* consistent with the output I see from the attached Glyphs source, which has an instance with

```
UPM = 1000
typoAscender = 800
typoDescender = -200
typoLineGap = 200 (expected)
winAscender = 1000 (expected)
hheaAscent = 1000 (expected)
hheaDescent = -200 (expected)
hheaLineGap = 0 (not expected, but consistent with UPM * 1.2 - hheaAscent - hheaDescent) 
```

[test.glyphs.zip](https://github.com/googlei18n/glyphsLib/files/579107/test.glyphs.zip)
