### ISSUE TITLE
Assign components in GlyphClassDef

### ISSUE THREAD

**Issue by brawer** [googlei18n/glyphsLib#99]
Currently, glyphsLib does not emit ligature components in `GlyphClassDef` of `table GDEF`, so the last argument to `GlyphClassDef` is always empty. Probably glyphsLib should indicate ligature components, but I haven’t been able to find out what logic is used by Glyphs. Maybe @schriftgestalt can tell?

**Comment by anthrotype** [comment]
I haven't checked Glyphs.app and haven't thought more than 3 minutes on it, but my naive algorithm would be: we know when a glyph is a "Ligature", i.e. `if has_caret or subCategory == 'Ligature'`, then we can check if that glyph has any components, and assign those to the category "Ligature Components"?

**Comment by anthrotype** [comment]
For reference, https://www.microsoft.com/typography/otspec/GDEF.htm

> Component glyphs can be put together to generate ligatures. A ligature can be generated by creating a glyph in the font that references the component glyphs, or outputting the component glyphs in the desired sequence.

I understand this to mean that "Ligature Components" are not just glyphs used as components in a composite ligature glyph, but also glyphs that are laid out via GSUB in a desired sequence to display a "ligature", but the latter does not necessarily exist as a separate glyph?

**Comment by schriftgestalt** [comment]
Glyphs puts the ligatures in the GDEF if the glyph has `caret_X` anchors.

**Comment by anthrotype** [comment]
I think Sascha was asking for GDEF ligature components, not ligatures.

**Comment by khaledhosny** [comment]
What is ligature component class good for? No lookup flags require them (unlike other glyph classes) and no other OTL handling makes use of it AFAIK.

Oh, I now saw the part of the spec describing it (that @anthrotype is referencing above as well), and I think we can just ignore it. Looks like some early OpenType idea that didn’t gain any traction.

**Comment by anthrotype** [comment]
I don't know what they are for. The very same quoted paragraph from the GDEF spec ends with

> Component glyphs are not used in defining any GSUB or GPOS formats.

which suggests these ligature components aren't actually used at all.

So maybe we can ignore them, like @khaledhosny suggested.

@schriftgestalt does Glyphs.app populate the fourth argument of the `GlyphClassDef` statement in the generated features.fea?

**Comment by brawer** [comment]
Apparently Glyphs.app never populates the fourth component of `GlyphClassDef`. Currently glyphsLib replicates this. Closing bug.
